// Generated by littledivy/ffigen
const _ = {
  // nk_init_fixed @ ./nuklear.h:613:16
  nk_init_fixed: {
    parameters: ["pointer","pointer","u64","pointer"],
    result: "i32",
  },
  // nk_init @ ./nuklear.h:631:16
  nk_init: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // nk_init_custom @ ./nuklear.h:650:16
  nk_init_custom: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // nk_clear @ ./nuklear.h:664:13
  nk_clear: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_free @ ./nuklear.h:677:13
  nk_free: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_input_begin @ ./nuklear.h:813:13
  nk_input_begin: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_input_motion @ ./nuklear.h:827:13
  nk_input_motion: {
    parameters: ["pointer","i32","i32"],
    result: "void",
  },
  // nk_input_char @ ./nuklear.h:890:13
  nk_input_char: {
    parameters: ["pointer","u8"],
    result: "void",
  },
  // nk_input_unicode @ ./nuklear.h:923:13
  nk_input_unicode: {
    parameters: ["pointer","u32"],
    result: "void",
  },
  // nk_input_end @ ./nuklear.h:936:13
  nk_input_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk__begin @ ./nuklear.h:1204:33
  nk__begin: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // nk__next @ ./nuklear.h:1219:33
  nk__next: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // nk_end @ ./nuklear.h:1538:13
  nk_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_window_find @ ./nuklear.h:1554:26
  nk_window_find: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // nk_window_get_width @ ./nuklear.h:1618:14
  nk_window_get_width: {
    parameters: ["pointer"],
    result: "f32",
  },
  // nk_window_get_height @ ./nuklear.h:1634:14
  nk_window_get_height: {
    parameters: ["pointer"],
    result: "f32",
  },
  // nk_window_get_panel @ ./nuklear.h:1652:25
  nk_window_get_panel: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // nk_window_get_canvas @ ./nuklear.h:1746:34
  nk_window_get_canvas: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // nk_window_get_scroll @ ./nuklear.h:1762:13
  nk_window_get_scroll: {
    parameters: ["pointer","pointer","pointer"],
    result: "void",
  },
  // nk_window_has_focus @ ./nuklear.h:1777:16
  nk_window_has_focus: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_window_is_hovered @ ./nuklear.h:1792:16
  nk_window_is_hovered: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_window_is_collapsed @ ./nuklear.h:1807:16
  nk_window_is_collapsed: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_window_is_closed @ ./nuklear.h:1821:16
  nk_window_is_closed: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_window_is_hidden @ ./nuklear.h:1835:16
  nk_window_is_hidden: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_window_is_active @ ./nuklear.h:1849:16
  nk_window_is_active: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_window_is_any_hovered @ ./nuklear.h:1862:16
  nk_window_is_any_hovered: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_item_is_any_active @ ./nuklear.h:1877:16
  nk_item_is_any_active: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_window_set_focus @ ./nuklear.h:1928:13
  nk_window_set_focus: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // nk_window_set_scroll @ ./nuklear.h:1944:13
  nk_window_set_scroll: {
    parameters: ["pointer","u32","u32"],
    result: "void",
  },
  // nk_window_close @ ./nuklear.h:1956:13
  nk_window_close: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // nk_layout_set_min_row_height @ ./nuklear.h:2327:13
  nk_layout_set_min_row_height: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // nk_layout_reset_min_row_height @ ./nuklear.h:2338:13
  nk_layout_reset_min_row_height: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_layout_ratio_from_pixel @ ./nuklear.h:2365:14
  nk_layout_ratio_from_pixel: {
    parameters: ["pointer","f32"],
    result: "f32",
  },
  // nk_layout_row_dynamic @ ./nuklear.h:2380:13
  nk_layout_row_dynamic: {
    parameters: ["pointer","f32","i32"],
    result: "void",
  },
  // nk_layout_row_static @ ./nuklear.h:2396:13
  nk_layout_row_static: {
    parameters: ["pointer","f32","i32","i32"],
    result: "void",
  },
  // nk_layout_row_push @ ./nuklear.h:2422:13
  nk_layout_row_push: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // nk_layout_row_end @ ./nuklear.h:2433:13
  nk_layout_row_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_layout_row_template_begin @ ./nuklear.h:2459:13
  nk_layout_row_template_begin: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // nk_layout_row_template_push_dynamic @ ./nuklear.h:2471:13
  nk_layout_row_template_push_dynamic: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_layout_row_template_push_variable @ ./nuklear.h:2483:13
  nk_layout_row_template_push_variable: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // nk_layout_row_template_push_static @ ./nuklear.h:2495:13
  nk_layout_row_template_push_static: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // nk_layout_row_template_end @ ./nuklear.h:2506:13
  nk_layout_row_template_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_layout_space_end @ ./nuklear.h:2543:13
  nk_layout_space_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_spacer @ ./nuklear.h:2625:13
  nk_spacer: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_group_begin @ ./nuklear.h:2730:16
  nk_group_begin: {
    parameters: ["pointer","pointer","u32"],
    result: "i32",
  },
  // nk_group_begin_titled @ ./nuklear.h:2746:16
  nk_group_begin_titled: {
    parameters: ["pointer","pointer","pointer","u32"],
    result: "i32",
  },
  // nk_group_end @ ./nuklear.h:2757:13
  nk_group_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_group_scrolled_offset_begin @ ./nuklear.h:2775:16
  nk_group_scrolled_offset_begin: {
    parameters: ["pointer","pointer","pointer","pointer","u32"],
    result: "i32",
  },
  // nk_group_scrolled_begin @ ./nuklear.h:2792:16
  nk_group_scrolled_begin: {
    parameters: ["pointer","pointer","pointer","u32"],
    result: "i32",
  },
  // nk_group_scrolled_end @ ./nuklear.h:2803:13
  nk_group_scrolled_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_group_get_scroll @ ./nuklear.h:2817:13
  nk_group_get_scroll: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "void",
  },
  // nk_group_set_scroll @ ./nuklear.h:2831:13
  nk_group_set_scroll: {
    parameters: ["pointer","pointer","u32","u32"],
    result: "void",
  },
  // nk_tree_pop @ ./nuklear.h:3035:13
  nk_tree_pop: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_tree_state_pop @ ./nuklear.h:3079:13
  nk_tree_state_pop: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_tree_element_pop @ ./nuklear.h:3085:13
  nk_tree_element_pop: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_list_view_begin @ ./nuklear.h:3101:16
  nk_list_view_begin: {
    parameters: ["pointer","pointer","pointer","u32","i32","i32"],
    result: "i32",
  },
  // nk_list_view_end @ ./nuklear.h:3102:13
  nk_list_view_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_widget_width @ ./nuklear.h:3129:14
  nk_widget_width: {
    parameters: ["pointer"],
    result: "f32",
  },
  // nk_widget_height @ ./nuklear.h:3130:14
  nk_widget_height: {
    parameters: ["pointer"],
    result: "f32",
  },
  // nk_widget_is_hovered @ ./nuklear.h:3131:16
  nk_widget_is_hovered: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_spacing @ ./nuklear.h:3134:13
  nk_spacing: {
    parameters: ["pointer","i32"],
    result: "void",
  },
  // nk_widget_disable_begin @ ./nuklear.h:3135:13
  nk_widget_disable_begin: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_widget_disable_end @ ./nuklear.h:3136:13
  nk_widget_disable_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_text @ ./nuklear.h:3155:13
  nk_text: {
    parameters: ["pointer","pointer","i32","u32"],
    result: "void",
  },
  // nk_text_wrap @ ./nuklear.h:3157:13
  nk_text_wrap: {
    parameters: ["pointer","pointer","i32"],
    result: "void",
  },
  // nk_label @ ./nuklear.h:3159:13
  nk_label: {
    parameters: ["pointer","pointer","u32"],
    result: "void",
  },
  // nk_label_wrap @ ./nuklear.h:3161:13
  nk_label_wrap: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // nk_button_text @ ./nuklear.h:3187:16
  nk_button_text: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // nk_button_label @ ./nuklear.h:3188:16
  nk_button_label: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_button_text_styled @ ./nuklear.h:3196:16
  nk_button_text_styled: {
    parameters: ["pointer","pointer","pointer","i32"],
    result: "i32",
  },
  // nk_button_label_styled @ ./nuklear.h:3197:16
  nk_button_label_styled: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // nk_button_pop_behavior @ ./nuklear.h:3206:16
  nk_button_pop_behavior: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_check_label @ ./nuklear.h:3212:16
  nk_check_label: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // nk_check_text @ ./nuklear.h:3213:16
  nk_check_text: {
    parameters: ["pointer","pointer","i32","i32"],
    result: "i32",
  },
  // nk_check_text_align @ ./nuklear.h:3214:16
  nk_check_text_align: {
    parameters: ["pointer","pointer","i32","i32","u32","u32"],
    result: "i32",
  },
  // nk_check_flags_label @ ./nuklear.h:3215:17
  nk_check_flags_label: {
    parameters: ["pointer","pointer","u32","u32"],
    result: "u32",
  },
  // nk_check_flags_text @ ./nuklear.h:3216:17
  nk_check_flags_text: {
    parameters: ["pointer","pointer","i32","u32","u32"],
    result: "u32",
  },
  // nk_checkbox_label @ ./nuklear.h:3217:16
  nk_checkbox_label: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // nk_checkbox_label_align @ ./nuklear.h:3218:16
  nk_checkbox_label_align: {
    parameters: ["pointer","pointer","pointer","u32","u32"],
    result: "i32",
  },
  // nk_checkbox_text @ ./nuklear.h:3219:16
  nk_checkbox_text: {
    parameters: ["pointer","pointer","i32","pointer"],
    result: "i32",
  },
  // nk_checkbox_text_align @ ./nuklear.h:3220:16
  nk_checkbox_text_align: {
    parameters: ["pointer","pointer","i32","pointer","u32","u32"],
    result: "i32",
  },
  // nk_checkbox_flags_label @ ./nuklear.h:3221:16
  nk_checkbox_flags_label: {
    parameters: ["pointer","pointer","pointer","u32"],
    result: "i32",
  },
  // nk_checkbox_flags_text @ ./nuklear.h:3222:16
  nk_checkbox_flags_text: {
    parameters: ["pointer","pointer","i32","pointer","u32"],
    result: "i32",
  },
  // nk_radio_label @ ./nuklear.h:3228:16
  nk_radio_label: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // nk_radio_label_align @ ./nuklear.h:3229:16
  nk_radio_label_align: {
    parameters: ["pointer","pointer","pointer","u32","u32"],
    result: "i32",
  },
  // nk_radio_text @ ./nuklear.h:3230:16
  nk_radio_text: {
    parameters: ["pointer","pointer","i32","pointer"],
    result: "i32",
  },
  // nk_radio_text_align @ ./nuklear.h:3231:16
  nk_radio_text_align: {
    parameters: ["pointer","pointer","i32","pointer","u32","u32"],
    result: "i32",
  },
  // nk_option_label @ ./nuklear.h:3232:16
  nk_option_label: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // nk_option_label_align @ ./nuklear.h:3233:16
  nk_option_label_align: {
    parameters: ["pointer","pointer","i32","u32","u32"],
    result: "i32",
  },
  // nk_option_text @ ./nuklear.h:3234:16
  nk_option_text: {
    parameters: ["pointer","pointer","i32","i32"],
    result: "i32",
  },
  // nk_option_text_align @ ./nuklear.h:3235:16
  nk_option_text_align: {
    parameters: ["pointer","pointer","i32","i32","u32","u32"],
    result: "i32",
  },
  // nk_selectable_label @ ./nuklear.h:3241:16
  nk_selectable_label: {
    parameters: ["pointer","pointer","u32","pointer"],
    result: "i32",
  },
  // nk_selectable_text @ ./nuklear.h:3242:16
  nk_selectable_text: {
    parameters: ["pointer","pointer","i32","u32","pointer"],
    result: "i32",
  },
  // nk_select_label @ ./nuklear.h:3248:16
  nk_select_label: {
    parameters: ["pointer","pointer","u32","i32"],
    result: "i32",
  },
  // nk_select_text @ ./nuklear.h:3249:16
  nk_select_text: {
    parameters: ["pointer","pointer","i32","u32","i32"],
    result: "i32",
  },
  // nk_slide_float @ ./nuklear.h:3260:14
  nk_slide_float: {
    parameters: ["pointer","f32","f32","f32","f32"],
    result: "f32",
  },
  // nk_slide_int @ ./nuklear.h:3261:12
  nk_slide_int: {
    parameters: ["pointer","i32","i32","i32","i32"],
    result: "i32",
  },
  // nk_slider_float @ ./nuklear.h:3262:16
  nk_slider_float: {
    parameters: ["pointer","f32","pointer","f32","f32"],
    result: "i32",
  },
  // nk_slider_int @ ./nuklear.h:3263:16
  nk_slider_int: {
    parameters: ["pointer","i32","pointer","i32","i32"],
    result: "i32",
  },
  // nk_progress @ ./nuklear.h:3278:16
  nk_progress: {
    parameters: ["pointer","pointer","u64","i32"],
    result: "i32",
  },
  // nk_prog @ ./nuklear.h:3279:16
  nk_prog: {
    parameters: ["pointer","u64","u64","i32"],
    result: "u64",
  },
  // nk_property_int @ ./nuklear.h:3384:13
  nk_property_int: {
    parameters: ["pointer","pointer","i32","pointer","i32","i32","f32"],
    result: "void",
  },
  // nk_property_float @ ./nuklear.h:3405:13
  nk_property_float: {
    parameters: ["pointer","pointer","f32","pointer","f32","f32","f32"],
    result: "void",
  },
  // nk_propertyi @ ./nuklear.h:3449:12
  nk_propertyi: {
    parameters: ["pointer","pointer","i32","i32","i32","i32","f32"],
    result: "i32",
  },
  // nk_propertyf @ ./nuklear.h:3472:14
  nk_propertyf: {
    parameters: ["pointer","pointer","f32","f32","f32","f32","f32"],
    result: "f32",
  },
  // nk_edit_string @ ./nuklear.h:3529:17
  nk_edit_string: {
    parameters: ["pointer","u32","pointer","pointer","i32","pointer"],
    result: "u32",
  },
  // nk_edit_string_zero_terminated @ ./nuklear.h:3530:17
  nk_edit_string_zero_terminated: {
    parameters: ["pointer","u32","pointer","i32","pointer"],
    result: "u32",
  },
  // nk_edit_buffer @ ./nuklear.h:3531:17
  nk_edit_buffer: {
    parameters: ["pointer","u32","pointer","pointer"],
    result: "u32",
  },
  // nk_edit_focus @ ./nuklear.h:3532:13
  nk_edit_focus: {
    parameters: ["pointer","u32"],
    result: "void",
  },
  // nk_edit_unfocus @ ./nuklear.h:3533:13
  nk_edit_unfocus: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_chart_push @ ./nuklear.h:3543:17
  nk_chart_push: {
    parameters: ["pointer","f32"],
    result: "u32",
  },
  // nk_chart_push_slot @ ./nuklear.h:3544:17
  nk_chart_push_slot: {
    parameters: ["pointer","f32","i32"],
    result: "u32",
  },
  // nk_chart_end @ ./nuklear.h:3545:13
  nk_chart_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_popup_close @ ./nuklear.h:3554:13
  nk_popup_close: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_popup_end @ ./nuklear.h:3555:13
  nk_popup_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_popup_get_scroll @ ./nuklear.h:3556:13
  nk_popup_get_scroll: {
    parameters: ["pointer","pointer","pointer"],
    result: "void",
  },
  // nk_popup_set_scroll @ ./nuklear.h:3557:13
  nk_popup_set_scroll: {
    parameters: ["pointer","u32","u32"],
    result: "void",
  },
  // nk_combo_item_label @ ./nuklear.h:3585:16
  nk_combo_item_label: {
    parameters: ["pointer","pointer","u32"],
    result: "i32",
  },
  // nk_combo_item_text @ ./nuklear.h:3586:16
  nk_combo_item_text: {
    parameters: ["pointer","pointer","i32","u32"],
    result: "i32",
  },
  // nk_combo_close @ ./nuklear.h:3591:13
  nk_combo_close: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_combo_end @ ./nuklear.h:3592:13
  nk_combo_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_contextual_item_text @ ./nuklear.h:3599:16
  nk_contextual_item_text: {
    parameters: ["pointer","pointer","i32","u32"],
    result: "i32",
  },
  // nk_contextual_item_label @ ./nuklear.h:3600:16
  nk_contextual_item_label: {
    parameters: ["pointer","pointer","u32"],
    result: "i32",
  },
  // nk_contextual_close @ ./nuklear.h:3605:13
  nk_contextual_close: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_contextual_end @ ./nuklear.h:3606:13
  nk_contextual_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_tooltip @ ./nuklear.h:3612:13
  nk_tooltip: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // nk_tooltip_begin @ ./nuklear.h:3617:16
  nk_tooltip_begin: {
    parameters: ["pointer","f32"],
    result: "i32",
  },
  // nk_tooltip_end @ ./nuklear.h:3618:13
  nk_tooltip_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_menubar_begin @ ./nuklear.h:3624:13
  nk_menubar_begin: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_menubar_end @ ./nuklear.h:3625:13
  nk_menubar_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_menu_item_text @ ./nuklear.h:3634:16
  nk_menu_item_text: {
    parameters: ["pointer","pointer","i32","u32"],
    result: "i32",
  },
  // nk_menu_item_label @ ./nuklear.h:3635:16
  nk_menu_item_label: {
    parameters: ["pointer","pointer","u32"],
    result: "i32",
  },
  // nk_menu_close @ ./nuklear.h:3640:13
  nk_menu_close: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_menu_end @ ./nuklear.h:3641:13
  nk_menu_end: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_style_default @ ./nuklear.h:3695:13
  nk_style_default: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_style_from_table @ ./nuklear.h:3696:13
  nk_style_from_table: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // nk_style_load_all_cursors @ ./nuklear.h:3698:13
  nk_style_load_all_cursors: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // nk_style_set_font @ ./nuklear.h:3700:13
  nk_style_set_font: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // nk_style_show_cursor @ ./nuklear.h:3702:13
  nk_style_show_cursor: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_style_hide_cursor @ ./nuklear.h:3703:13
  nk_style_hide_cursor: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_style_push_font @ ./nuklear.h:3705:16
  nk_style_push_font: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_style_push_float @ ./nuklear.h:3706:16
  nk_style_push_float: {
    parameters: ["pointer","pointer","f32"],
    result: "i32",
  },
  // nk_style_push_style_item @ ./nuklear.h:3708:16
  nk_style_push_style_item: {
    parameters: ["pointer","pointer",{"struct":[]}],
    result: "i32",
  },
  // nk_style_push_flags @ ./nuklear.h:3709:16
  nk_style_push_flags: {
    parameters: ["pointer","pointer","u32"],
    result: "i32",
  },
  // nk_style_pop_font @ ./nuklear.h:3712:16
  nk_style_pop_font: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_style_pop_float @ ./nuklear.h:3713:16
  nk_style_pop_float: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_style_pop_vec2 @ ./nuklear.h:3714:16
  nk_style_pop_vec2: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_style_pop_style_item @ ./nuklear.h:3715:16
  nk_style_pop_style_item: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_style_pop_flags @ ./nuklear.h:3716:16
  nk_style_pop_flags: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_style_pop_color @ ./nuklear.h:3717:16
  nk_style_pop_color: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_image_is_subimage @ ./nuklear.h:3792:16
  nk_image_is_subimage: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_nine_slice_is_sub9slice @ ./nuklear.h:3804:12
  nk_nine_slice_is_sub9slice: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_murmur_hash @ ./nuklear.h:3813:16
  nk_murmur_hash: {
    parameters: ["pointer","i32","u32"],
    result: "u32",
  },
  // nk_strlen @ ./nuklear.h:3834:12
  nk_strlen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_stricmp @ ./nuklear.h:3835:12
  nk_stricmp: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_stricmpn @ ./nuklear.h:3836:12
  nk_stricmpn: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // nk_strtoi @ ./nuklear.h:3837:12
  nk_strtoi: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_strtof @ ./nuklear.h:3838:14
  nk_strtof: {
    parameters: ["pointer","pointer"],
    result: "f32",
  },
  // nk_strfilter @ ./nuklear.h:3843:12
  nk_strfilter: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_strmatch_fuzzy_string @ ./nuklear.h:3844:12
  nk_strmatch_fuzzy_string: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // nk_strmatch_fuzzy_text @ ./nuklear.h:3845:12
  nk_strmatch_fuzzy_text: {
    parameters: ["pointer","i32","pointer","pointer"],
    result: "i32",
  },
  // nk_utf_decode @ ./nuklear.h:3851:12
  nk_utf_decode: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // nk_utf_encode @ ./nuklear.h:3852:12
  nk_utf_encode: {
    parameters: ["u32","pointer","i32"],
    result: "i32",
  },
  // nk_utf_len @ ./nuklear.h:3853:12
  nk_utf_len: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // nk_utf_at @ ./nuklear.h:3854:20
  nk_utf_at: {
    parameters: ["pointer","i32","i32","pointer","pointer"],
    result: "pointer",
  },
  // nk_buffer_init @ ./nuklear.h:4258:13
  nk_buffer_init: {
    parameters: ["pointer","pointer","u64"],
    result: "void",
  },
  // nk_buffer_init_fixed @ ./nuklear.h:4259:13
  nk_buffer_init_fixed: {
    parameters: ["pointer","pointer","u64"],
    result: "void",
  },
  // nk_buffer_info @ ./nuklear.h:4260:13
  nk_buffer_info: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // nk_buffer_clear @ ./nuklear.h:4264:13
  nk_buffer_clear: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_buffer_free @ ./nuklear.h:4265:13
  nk_buffer_free: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_buffer_memory @ ./nuklear.h:4266:14
  nk_buffer_memory: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // nk_buffer_memory_const @ ./nuklear.h:4267:20
  nk_buffer_memory_const: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // nk_buffer_total @ ./nuklear.h:4268:16
  nk_buffer_total: {
    parameters: ["pointer"],
    result: "u64",
  },
  // nk_str_init @ ./nuklear.h:4288:13
  nk_str_init: {
    parameters: ["pointer","pointer","u64"],
    result: "void",
  },
  // nk_str_init_fixed @ ./nuklear.h:4289:13
  nk_str_init_fixed: {
    parameters: ["pointer","pointer","u64"],
    result: "void",
  },
  // nk_str_clear @ ./nuklear.h:4290:13
  nk_str_clear: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_str_free @ ./nuklear.h:4291:13
  nk_str_free: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_str_append_text_char @ ./nuklear.h:4293:12
  nk_str_append_text_char: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // nk_str_append_str_char @ ./nuklear.h:4294:12
  nk_str_append_str_char: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_str_append_text_utf8 @ ./nuklear.h:4295:12
  nk_str_append_text_utf8: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // nk_str_append_str_utf8 @ ./nuklear.h:4296:12
  nk_str_append_str_utf8: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_str_append_text_runes @ ./nuklear.h:4297:12
  nk_str_append_text_runes: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // nk_str_append_str_runes @ ./nuklear.h:4298:12
  nk_str_append_str_runes: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // nk_str_insert_at_char @ ./nuklear.h:4300:12
  nk_str_insert_at_char: {
    parameters: ["pointer","i32","pointer","i32"],
    result: "i32",
  },
  // nk_str_insert_at_rune @ ./nuklear.h:4301:12
  nk_str_insert_at_rune: {
    parameters: ["pointer","i32","pointer","i32"],
    result: "i32",
  },
  // nk_str_insert_text_char @ ./nuklear.h:4303:12
  nk_str_insert_text_char: {
    parameters: ["pointer","i32","pointer","i32"],
    result: "i32",
  },
  // nk_str_insert_str_char @ ./nuklear.h:4304:12
  nk_str_insert_str_char: {
    parameters: ["pointer","i32","pointer"],
    result: "i32",
  },
  // nk_str_insert_text_utf8 @ ./nuklear.h:4305:12
  nk_str_insert_text_utf8: {
    parameters: ["pointer","i32","pointer","i32"],
    result: "i32",
  },
  // nk_str_insert_str_utf8 @ ./nuklear.h:4306:12
  nk_str_insert_str_utf8: {
    parameters: ["pointer","i32","pointer"],
    result: "i32",
  },
  // nk_str_insert_text_runes @ ./nuklear.h:4307:12
  nk_str_insert_text_runes: {
    parameters: ["pointer","i32","pointer","i32"],
    result: "i32",
  },
  // nk_str_insert_str_runes @ ./nuklear.h:4308:12
  nk_str_insert_str_runes: {
    parameters: ["pointer","i32","pointer"],
    result: "i32",
  },
  // nk_str_remove_chars @ ./nuklear.h:4310:13
  nk_str_remove_chars: {
    parameters: ["pointer","i32"],
    result: "void",
  },
  // nk_str_remove_runes @ ./nuklear.h:4311:13
  nk_str_remove_runes: {
    parameters: ["pointer","i32"],
    result: "void",
  },
  // nk_str_delete_chars @ ./nuklear.h:4312:13
  nk_str_delete_chars: {
    parameters: ["pointer","i32","i32"],
    result: "void",
  },
  // nk_str_delete_runes @ ./nuklear.h:4313:13
  nk_str_delete_runes: {
    parameters: ["pointer","i32","i32"],
    result: "void",
  },
  // nk_str_at_char @ ./nuklear.h:4315:14
  nk_str_at_char: {
    parameters: ["pointer","i32"],
    result: "pointer",
  },
  // nk_str_at_rune @ ./nuklear.h:4316:14
  nk_str_at_rune: {
    parameters: ["pointer","i32","pointer","pointer"],
    result: "pointer",
  },
  // nk_str_rune_at @ ./nuklear.h:4317:16
  nk_str_rune_at: {
    parameters: ["pointer","i32"],
    result: "u32",
  },
  // nk_str_at_char_const @ ./nuklear.h:4318:20
  nk_str_at_char_const: {
    parameters: ["pointer","i32"],
    result: "pointer",
  },
  // nk_str_at_const @ ./nuklear.h:4319:20
  nk_str_at_const: {
    parameters: ["pointer","i32","pointer","pointer"],
    result: "pointer",
  },
  // nk_str_get @ ./nuklear.h:4321:14
  nk_str_get: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // nk_str_get_const @ ./nuklear.h:4322:20
  nk_str_get_const: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // nk_str_len @ ./nuklear.h:4323:12
  nk_str_len: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_str_len_char @ ./nuklear.h:4324:12
  nk_str_len_char: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_filter_default @ ./nuklear.h:4418:16
  nk_filter_default: {
    parameters: ["pointer","u32"],
    result: "i32",
  },
  // nk_filter_ascii @ ./nuklear.h:4419:16
  nk_filter_ascii: {
    parameters: ["pointer","u32"],
    result: "i32",
  },
  // nk_filter_float @ ./nuklear.h:4420:16
  nk_filter_float: {
    parameters: ["pointer","u32"],
    result: "i32",
  },
  // nk_filter_decimal @ ./nuklear.h:4421:16
  nk_filter_decimal: {
    parameters: ["pointer","u32"],
    result: "i32",
  },
  // nk_filter_hex @ ./nuklear.h:4422:16
  nk_filter_hex: {
    parameters: ["pointer","u32"],
    result: "i32",
  },
  // nk_filter_oct @ ./nuklear.h:4423:16
  nk_filter_oct: {
    parameters: ["pointer","u32"],
    result: "i32",
  },
  // nk_filter_binary @ ./nuklear.h:4424:16
  nk_filter_binary: {
    parameters: ["pointer","u32"],
    result: "i32",
  },
  // nk_textedit_init @ ./nuklear.h:4430:13
  nk_textedit_init: {
    parameters: ["pointer","pointer","u64"],
    result: "void",
  },
  // nk_textedit_init_fixed @ ./nuklear.h:4431:13
  nk_textedit_init_fixed: {
    parameters: ["pointer","pointer","u64"],
    result: "void",
  },
  // nk_textedit_free @ ./nuklear.h:4432:13
  nk_textedit_free: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_textedit_text @ ./nuklear.h:4433:13
  nk_textedit_text: {
    parameters: ["pointer","pointer","i32"],
    result: "void",
  },
  // nk_textedit_delete @ ./nuklear.h:4434:13
  nk_textedit_delete: {
    parameters: ["pointer","i32","i32"],
    result: "void",
  },
  // nk_textedit_delete_selection @ ./nuklear.h:4435:13
  nk_textedit_delete_selection: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_textedit_select_all @ ./nuklear.h:4436:13
  nk_textedit_select_all: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_textedit_cut @ ./nuklear.h:4437:16
  nk_textedit_cut: {
    parameters: ["pointer"],
    result: "i32",
  },
  // nk_textedit_paste @ ./nuklear.h:4438:16
  nk_textedit_paste: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // nk_textedit_undo @ ./nuklear.h:4439:13
  nk_textedit_undo: {
    parameters: ["pointer"],
    result: "void",
  },
  // nk_textedit_redo @ ./nuklear.h:4440:13
  nk_textedit_redo: {
    parameters: ["pointer"],
    result: "void",
  }
} as const;

const { symbols } = Deno.dlopen("libnuklear.so", _);

export default symbols;

