// Generated by littledivy/ffigen
const _ = {
  // mp3dec_init @ ./minimp3.h:29:6
  mp3dec_init: {
    parameters: ["pointer"],
    result: "void",
  },
  // mp3dec_decode_frame @ ./minimp3.h:36:5
  mp3dec_decode_frame: {
    parameters: ["pointer","pointer","i32","pointer","pointer"],
    result: "i32",
  }
} as const;

const { symbols } = Deno.dlopen("libminimp3.so", _);

export default symbols;

