// Generated by littledivy/ffigen
const _ = {
  // sapp_width @ ./sokol_app.h:1782:24
  sapp_width: {
    parameters: [],
    result: "i32",
  },
  // sapp_widthf @ ./sokol_app.h:1784:26
  sapp_widthf: {
    parameters: [],
    result: "f32",
  },
  // sapp_height @ ./sokol_app.h:1786:24
  sapp_height: {
    parameters: [],
    result: "i32",
  },
  // sapp_heightf @ ./sokol_app.h:1788:26
  sapp_heightf: {
    parameters: [],
    result: "f32",
  },
  // sapp_color_format @ ./sokol_app.h:1790:24
  sapp_color_format: {
    parameters: [],
    result: "i32",
  },
  // sapp_depth_format @ ./sokol_app.h:1792:24
  sapp_depth_format: {
    parameters: [],
    result: "i32",
  },
  // sapp_sample_count @ ./sokol_app.h:1794:24
  sapp_sample_count: {
    parameters: [],
    result: "i32",
  },
  // sapp_dpi_scale @ ./sokol_app.h:1798:26
  sapp_dpi_scale: {
    parameters: [],
    result: "f32",
  },
  // sapp_toggle_fullscreen @ ./sokol_app.h:1806:25
  sapp_toggle_fullscreen: {
    parameters: [],
    result: "void",
  },
  // sapp_userdata @ ./sokol_app.h:1820:26
  sapp_userdata: {
    parameters: [],
    result: "pointer",
  },
  // sapp_request_quit @ ./sokol_app.h:1824:25
  sapp_request_quit: {
    parameters: [],
    result: "void",
  },
  // sapp_cancel_quit @ ./sokol_app.h:1826:25
  sapp_cancel_quit: {
    parameters: [],
    result: "void",
  },
  // sapp_quit @ ./sokol_app.h:1828:25
  sapp_quit: {
    parameters: [],
    result: "void",
  },
  // sapp_consume_event @ ./sokol_app.h:1830:25
  sapp_consume_event: {
    parameters: [],
    result: "void",
  },
  // sapp_frame_count @ ./sokol_app.h:1832:29
  sapp_frame_count: {
    parameters: [],
    result: "u64",
  },
  // sapp_set_clipboard_string @ ./sokol_app.h:1836:25
  sapp_set_clipboard_string: {
    parameters: ["pointer"],
    result: "void",
  },
  // sapp_get_clipboard_string @ ./sokol_app.h:1838:32
  sapp_get_clipboard_string: {
    parameters: [],
    result: "pointer",
  },
  // sapp_set_window_title @ ./sokol_app.h:1840:25
  sapp_set_window_title: {
    parameters: ["pointer"],
    result: "void",
  },
  // sapp_set_icon @ ./sokol_app.h:1842:25
  sapp_set_icon: {
    parameters: ["pointer"],
    result: "void",
  },
  // sapp_get_num_dropped_files @ ./sokol_app.h:1844:24
  sapp_get_num_dropped_files: {
    parameters: [],
    result: "i32",
  },
  // sapp_get_dropped_file_path @ ./sokol_app.h:1846:32
  sapp_get_dropped_file_path: {
    parameters: ["i32"],
    result: "pointer",
  },
  // sapp_run @ ./sokol_app.h:1849:25
  sapp_run: {
    parameters: ["pointer"],
    result: "void",
  },
  // sapp_egl_get_display @ ./sokol_app.h:1852:32
  sapp_egl_get_display: {
    parameters: [],
    result: "pointer",
  },
  // sapp_egl_get_context @ ./sokol_app.h:1854:32
  sapp_egl_get_context: {
    parameters: [],
    result: "pointer",
  },
  // sapp_html5_get_dropped_file_size @ ./sokol_app.h:1859:29
  sapp_html5_get_dropped_file_size: {
    parameters: ["i32"],
    result: "u32",
  },
  // sapp_html5_fetch_dropped_file @ ./sokol_app.h:1861:25
  sapp_html5_fetch_dropped_file: {
    parameters: ["pointer"],
    result: "void",
  },
  // sapp_metal_get_device @ ./sokol_app.h:1864:32
  sapp_metal_get_device: {
    parameters: [],
    result: "pointer",
  },
  // sapp_metal_get_current_drawable @ ./sokol_app.h:1866:32
  sapp_metal_get_current_drawable: {
    parameters: [],
    result: "pointer",
  },
  // sapp_metal_get_depth_stencil_texture @ ./sokol_app.h:1868:32
  sapp_metal_get_depth_stencil_texture: {
    parameters: [],
    result: "pointer",
  },
  // sapp_metal_get_msaa_color_texture @ ./sokol_app.h:1870:32
  sapp_metal_get_msaa_color_texture: {
    parameters: [],
    result: "pointer",
  },
  // sapp_macos_get_window @ ./sokol_app.h:1872:32
  sapp_macos_get_window: {
    parameters: [],
    result: "pointer",
  },
  // sapp_ios_get_window @ ./sokol_app.h:1874:32
  sapp_ios_get_window: {
    parameters: [],
    result: "pointer",
  },
  // sapp_d3d11_get_device @ ./sokol_app.h:1877:32
  sapp_d3d11_get_device: {
    parameters: [],
    result: "pointer",
  },
  // sapp_d3d11_get_device_context @ ./sokol_app.h:1879:32
  sapp_d3d11_get_device_context: {
    parameters: [],
    result: "pointer",
  },
  // sapp_d3d11_get_swap_chain @ ./sokol_app.h:1881:32
  sapp_d3d11_get_swap_chain: {
    parameters: [],
    result: "pointer",
  },
  // sapp_d3d11_get_render_view @ ./sokol_app.h:1883:32
  sapp_d3d11_get_render_view: {
    parameters: [],
    result: "pointer",
  },
  // sapp_d3d11_get_resolve_view @ ./sokol_app.h:1885:32
  sapp_d3d11_get_resolve_view: {
    parameters: [],
    result: "pointer",
  },
  // sapp_d3d11_get_depth_stencil_view @ ./sokol_app.h:1887:32
  sapp_d3d11_get_depth_stencil_view: {
    parameters: [],
    result: "pointer",
  },
  // sapp_win32_get_hwnd @ ./sokol_app.h:1889:32
  sapp_win32_get_hwnd: {
    parameters: [],
    result: "pointer",
  },
  // sapp_wgpu_get_device @ ./sokol_app.h:1892:32
  sapp_wgpu_get_device: {
    parameters: [],
    result: "pointer",
  },
  // sapp_wgpu_get_render_view @ ./sokol_app.h:1894:32
  sapp_wgpu_get_render_view: {
    parameters: [],
    result: "pointer",
  },
  // sapp_wgpu_get_resolve_view @ ./sokol_app.h:1896:32
  sapp_wgpu_get_resolve_view: {
    parameters: [],
    result: "pointer",
  },
  // sapp_wgpu_get_depth_stencil_view @ ./sokol_app.h:1898:32
  sapp_wgpu_get_depth_stencil_view: {
    parameters: [],
    result: "pointer",
  },
  // sapp_gl_get_framebuffer @ ./sokol_app.h:1901:29
  sapp_gl_get_framebuffer: {
    parameters: [],
    result: "u32",
  },
  // sapp_gl_get_major_version @ ./sokol_app.h:1903:24
  sapp_gl_get_major_version: {
    parameters: [],
    result: "i32",
  },
  // sapp_gl_get_minor_version @ ./sokol_app.h:1905:24
  sapp_gl_get_minor_version: {
    parameters: [],
    result: "i32",
  },
  // sapp_android_get_native_activity @ ./sokol_app.h:1908:32
  sapp_android_get_native_activity: {
    parameters: [],
    result: "pointer",
  }
} as const;

const { symbols } = Deno.dlopen("sokol.so", _);

export default symbols;

