// Generated by littledivy/ffigen
const _ = {
  // __sched_cpucount @ /usr/include/bits/cpu-set.h:117:12
  __sched_cpucount: {
    parameters: ["u64","pointer"],
    result: "i32",
  },
  // __sched_cpualloc @ /usr/include/bits/cpu-set.h:119:19
  __sched_cpualloc: {
    parameters: ["u64"],
    result: "pointer",
  },
  // __sched_cpufree @ /usr/include/bits/cpu-set.h:120:13
  __sched_cpufree: {
    parameters: ["pointer"],
    result: "void",
  },
  // sched_setparam @ /usr/include/sched.h:54:12
  sched_setparam: {
    parameters: ["i32","pointer"],
    result: "i32",
  },
  // sched_getparam @ /usr/include/sched.h:58:12
  sched_getparam: {
    parameters: ["i32","pointer"],
    result: "i32",
  },
  // sched_setscheduler @ /usr/include/sched.h:61:12
  sched_setscheduler: {
    parameters: ["i32","i32","pointer"],
    result: "i32",
  },
  // sched_getscheduler @ /usr/include/sched.h:65:12
  sched_getscheduler: {
    parameters: ["i32"],
    result: "i32",
  },
  // sched_yield @ /usr/include/sched.h:68:12
  sched_yield: {
    parameters: [],
    result: "i32",
  },
  // sched_get_priority_max @ /usr/include/sched.h:71:12
  sched_get_priority_max: {
    parameters: ["i32"],
    result: "i32",
  },
  // sched_get_priority_min @ /usr/include/sched.h:74:12
  sched_get_priority_min: {
    parameters: ["i32"],
    result: "i32",
  },
  // sched_rr_get_interval @ /usr/include/sched.h:78:12
  sched_rr_get_interval: {
    parameters: ["i32","pointer"],
    result: "i32",
  },
  // clock @ /usr/include/time.h:72:16
  clock: {
    parameters: [],
    result: "i64",
  },
  // time @ /usr/include/time.h:76:15
  time: {
    parameters: ["pointer"],
    result: "i64",
  },
  // mktime @ /usr/include/time.h:82:15
  mktime: {
    parameters: ["pointer"],
    result: "i64",
  },
  // strftime @ /usr/include/time.h:99:15
  strftime: {
    parameters: ["pointer","u64","pointer","pointer"],
    result: "u64",
  },
  // strftime_l @ /usr/include/time.h:116:15
  strftime_l: {
    parameters: ["pointer","u64","pointer","pointer","pointer"],
    result: "u64",
  },
  // gmtime @ /usr/include/time.h:132:19
  gmtime: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // localtime @ /usr/include/time.h:136:19
  localtime: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // gmtime_r @ /usr/include/time.h:154:19
  gmtime_r: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // localtime_r @ /usr/include/time.h:159:19
  localtime_r: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // asctime @ /usr/include/time.h:179:14
  asctime: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ctime @ /usr/include/time.h:183:14
  ctime: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // asctime_r @ /usr/include/time.h:197:14
  asctime_r: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // ctime_r @ /usr/include/time.h:202:14
  ctime_r: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // tzset @ /usr/include/time.h:228:13
  tzset: {
    parameters: [],
    result: "void",
  },
  // timegm @ /usr/include/time.h:246:15
  timegm: {
    parameters: ["pointer"],
    result: "i64",
  },
  // timelocal @ /usr/include/time.h:263:15
  timelocal: {
    parameters: ["pointer"],
    result: "i64",
  },
  // dysize @ /usr/include/time.h:271:12
  dysize: {
    parameters: ["i32"],
    result: "i32",
  },
  // nanosleep @ /usr/include/time.h:281:12
  nanosleep: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // clock_getres @ /usr/include/time.h:285:12
  clock_getres: {
    parameters: ["i32","pointer"],
    result: "i32",
  },
  // clock_gettime @ /usr/include/time.h:288:12
  clock_gettime: {
    parameters: ["i32","pointer"],
    result: "i32",
  },
  // clock_settime @ /usr/include/time.h:292:12
  clock_settime: {
    parameters: ["i32","pointer"],
    result: "i32",
  },
  // clock_nanosleep @ /usr/include/time.h:323:12
  clock_nanosleep: {
    parameters: ["i32","i32","pointer","pointer"],
    result: "i32",
  },
  // clock_getcpuclockid @ /usr/include/time.h:338:12
  clock_getcpuclockid: {
    parameters: ["i32","pointer"],
    result: "i32",
  },
  // timer_create @ /usr/include/time.h:343:12
  timer_create: {
    parameters: ["i32","pointer","pointer"],
    result: "i32",
  },
  // timer_delete @ /usr/include/time.h:348:12
  timer_delete: {
    parameters: ["pointer"],
    result: "i32",
  },
  // timer_settime @ /usr/include/time.h:352:12
  timer_settime: {
    parameters: ["pointer","i32","pointer","pointer"],
    result: "i32",
  },
  // timer_gettime @ /usr/include/time.h:357:12
  timer_gettime: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // timer_getoverrun @ /usr/include/time.h:376:12
  timer_getoverrun: {
    parameters: ["pointer"],
    result: "i32",
  },
  // timespec_get @ /usr/include/time.h:383:12
  timespec_get: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_create @ /usr/include/pthread.h:202:12
  pthread_create: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // pthread_exit @ /usr/include/pthread.h:211:13
  pthread_exit: {
    parameters: ["pointer"],
    result: "void",
  },
  // pthread_join @ /usr/include/pthread.h:219:12
  pthread_join: {
    parameters: ["u64","pointer"],
    result: "i32",
  },
  // pthread_detach @ /usr/include/pthread.h:269:12
  pthread_detach: {
    parameters: ["u64"],
    result: "i32",
  },
  // pthread_self @ /usr/include/pthread.h:273:18
  pthread_self: {
    parameters: [],
    result: "u64",
  },
  // pthread_equal @ /usr/include/pthread.h:276:12
  pthread_equal: {
    parameters: ["u64","u64"],
    result: "i32",
  },
  // pthread_attr_init @ /usr/include/pthread.h:285:12
  pthread_attr_init: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_attr_destroy @ /usr/include/pthread.h:288:12
  pthread_attr_destroy: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_attr_getdetachstate @ /usr/include/pthread.h:292:12
  pthread_attr_getdetachstate: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_setdetachstate @ /usr/include/pthread.h:297:12
  pthread_attr_setdetachstate: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_attr_getguardsize @ /usr/include/pthread.h:303:12
  pthread_attr_getguardsize: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_setguardsize @ /usr/include/pthread.h:308:12
  pthread_attr_setguardsize: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // pthread_attr_getschedparam @ /usr/include/pthread.h:314:12
  pthread_attr_getschedparam: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_setschedparam @ /usr/include/pthread.h:319:12
  pthread_attr_setschedparam: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_getschedpolicy @ /usr/include/pthread.h:324:12
  pthread_attr_getschedpolicy: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_setschedpolicy @ /usr/include/pthread.h:329:12
  pthread_attr_setschedpolicy: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_attr_getinheritsched @ /usr/include/pthread.h:333:12
  pthread_attr_getinheritsched: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_setinheritsched @ /usr/include/pthread.h:338:12
  pthread_attr_setinheritsched: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_attr_getscope @ /usr/include/pthread.h:344:12
  pthread_attr_getscope: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_setscope @ /usr/include/pthread.h:349:12
  pthread_attr_setscope: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_attr_getstackaddr @ /usr/include/pthread.h:353:12
  pthread_attr_getstackaddr: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_setstackaddr @ /usr/include/pthread.h:361:12
  pthread_attr_setstackaddr: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_getstacksize @ /usr/include/pthread.h:366:12
  pthread_attr_getstacksize: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_setstacksize @ /usr/include/pthread.h:373:12
  pthread_attr_setstacksize: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // pthread_attr_getstack @ /usr/include/pthread.h:379:12
  pthread_attr_getstack: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // pthread_attr_setstack @ /usr/include/pthread.h:387:12
  pthread_attr_setstack: {
    parameters: ["pointer","pointer","u64"],
    result: "i32",
  },
  // pthread_setschedparam @ /usr/include/pthread.h:441:12
  pthread_setschedparam: {
    parameters: ["u64","i32","pointer"],
    result: "i32",
  },
  // pthread_getschedparam @ /usr/include/pthread.h:446:12
  pthread_getschedparam: {
    parameters: ["u64","pointer","pointer"],
    result: "i32",
  },
  // pthread_setschedprio @ /usr/include/pthread.h:452:12
  pthread_setschedprio: {
    parameters: ["u64","i32"],
    result: "i32",
  },
  // pthread_once @ /usr/include/pthread.h:509:12
  pthread_once: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_setcancelstate @ /usr/include/pthread.h:521:12
  pthread_setcancelstate: {
    parameters: ["i32","pointer"],
    result: "i32",
  },
  // pthread_setcanceltype @ /usr/include/pthread.h:525:12
  pthread_setcanceltype: {
    parameters: ["i32","pointer"],
    result: "i32",
  },
  // pthread_cancel @ /usr/include/pthread.h:528:12
  pthread_cancel: {
    parameters: ["u64"],
    result: "i32",
  },
  // pthread_testcancel @ /usr/include/pthread.h:533:13
  pthread_testcancel: {
    parameters: [],
    result: "void",
  },
  // __pthread_register_cancel @ /usr/include/pthread.h:697:13
  __pthread_register_cancel: {
    parameters: ["pointer"],
    result: "void",
  },
  // __pthread_unregister_cancel @ /usr/include/pthread.h:709:13
  __pthread_unregister_cancel: {
    parameters: ["pointer"],
    result: "void",
  },
  // __pthread_unwind_next @ /usr/include/pthread.h:750:13
  __pthread_unwind_next: {
    parameters: ["pointer"],
    result: "void",
  },
  // pthread_mutex_init @ /usr/include/pthread.h:781:12
  pthread_mutex_init: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_mutex_destroy @ /usr/include/pthread.h:786:12
  pthread_mutex_destroy: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_mutex_trylock @ /usr/include/pthread.h:790:12
  pthread_mutex_trylock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_mutex_lock @ /usr/include/pthread.h:794:12
  pthread_mutex_lock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_mutex_timedlock @ /usr/include/pthread.h:800:12
  pthread_mutex_timedlock: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_mutex_unlock @ /usr/include/pthread.h:835:12
  pthread_mutex_unlock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_mutex_getprioceiling @ /usr/include/pthread.h:840:12
  pthread_mutex_getprioceiling: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_mutex_setprioceiling @ /usr/include/pthread.h:847:12
  pthread_mutex_setprioceiling: {
    parameters: ["pointer","i32","pointer"],
    result: "i32",
  },
  // pthread_mutex_consistent @ /usr/include/pthread.h:855:12
  pthread_mutex_consistent: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_mutexattr_init @ /usr/include/pthread.h:874:12
  pthread_mutexattr_init: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_mutexattr_destroy @ /usr/include/pthread.h:878:12
  pthread_mutexattr_destroy: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_mutexattr_getpshared @ /usr/include/pthread.h:882:12
  pthread_mutexattr_getpshared: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_mutexattr_setpshared @ /usr/include/pthread.h:888:12
  pthread_mutexattr_setpshared: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_mutexattr_gettype @ /usr/include/pthread.h:894:12
  pthread_mutexattr_gettype: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_mutexattr_settype @ /usr/include/pthread.h:901:12
  pthread_mutexattr_settype: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_mutexattr_getprotocol @ /usr/include/pthread.h:906:12
  pthread_mutexattr_getprotocol: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_mutexattr_setprotocol @ /usr/include/pthread.h:913:12
  pthread_mutexattr_setprotocol: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_mutexattr_getprioceiling @ /usr/include/pthread.h:918:12
  pthread_mutexattr_getprioceiling: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_mutexattr_setprioceiling @ /usr/include/pthread.h:924:12
  pthread_mutexattr_setprioceiling: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_mutexattr_getrobust @ /usr/include/pthread.h:930:12
  pthread_mutexattr_getrobust: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_mutexattr_setrobust @ /usr/include/pthread.h:946:12
  pthread_mutexattr_setrobust: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_rwlock_init @ /usr/include/pthread.h:967:12
  pthread_rwlock_init: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_rwlock_destroy @ /usr/include/pthread.h:972:12
  pthread_rwlock_destroy: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_rwlock_rdlock @ /usr/include/pthread.h:976:12
  pthread_rwlock_rdlock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_rwlock_tryrdlock @ /usr/include/pthread.h:980:12
  pthread_rwlock_tryrdlock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_rwlock_timedrdlock @ /usr/include/pthread.h:986:12
  pthread_rwlock_timedrdlock: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_rwlock_wrlock @ /usr/include/pthread.h:1023:12
  pthread_rwlock_wrlock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_rwlock_trywrlock @ /usr/include/pthread.h:1027:12
  pthread_rwlock_trywrlock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_rwlock_timedwrlock @ /usr/include/pthread.h:1033:12
  pthread_rwlock_timedwrlock: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_rwlock_unlock @ /usr/include/pthread.h:1071:12
  pthread_rwlock_unlock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_rwlockattr_init @ /usr/include/pthread.h:1078:12
  pthread_rwlockattr_init: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_rwlockattr_destroy @ /usr/include/pthread.h:1082:12
  pthread_rwlockattr_destroy: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_rwlockattr_getpshared @ /usr/include/pthread.h:1086:12
  pthread_rwlockattr_getpshared: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_rwlockattr_setpshared @ /usr/include/pthread.h:1092:12
  pthread_rwlockattr_setpshared: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_rwlockattr_getkind_np @ /usr/include/pthread.h:1097:12
  pthread_rwlockattr_getkind_np: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_rwlockattr_setkind_np @ /usr/include/pthread.h:1103:12
  pthread_rwlockattr_setkind_np: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_cond_init @ /usr/include/pthread.h:1112:12
  pthread_cond_init: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_cond_destroy @ /usr/include/pthread.h:1117:12
  pthread_cond_destroy: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_cond_signal @ /usr/include/pthread.h:1121:12
  pthread_cond_signal: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_cond_broadcast @ /usr/include/pthread.h:1125:12
  pthread_cond_broadcast: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_cond_wait @ /usr/include/pthread.h:1133:12
  pthread_cond_wait: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_cond_timedwait @ /usr/include/pthread.h:1145:12
  pthread_cond_timedwait: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // pthread_condattr_init @ /usr/include/pthread.h:1194:12
  pthread_condattr_init: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_condattr_destroy @ /usr/include/pthread.h:1198:12
  pthread_condattr_destroy: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_condattr_getpshared @ /usr/include/pthread.h:1202:12
  pthread_condattr_getpshared: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_condattr_setpshared @ /usr/include/pthread.h:1208:12
  pthread_condattr_setpshared: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_condattr_getclock @ /usr/include/pthread.h:1213:12
  pthread_condattr_getclock: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_condattr_setclock @ /usr/include/pthread.h:1219:12
  pthread_condattr_setclock: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_spin_init @ /usr/include/pthread.h:1230:12
  pthread_spin_init: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_spin_destroy @ /usr/include/pthread.h:1234:12
  pthread_spin_destroy: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_spin_lock @ /usr/include/pthread.h:1238:12
  pthread_spin_lock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_spin_trylock @ /usr/include/pthread.h:1242:12
  pthread_spin_trylock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_spin_unlock @ /usr/include/pthread.h:1246:12
  pthread_spin_unlock: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_barrier_init @ /usr/include/pthread.h:1254:12
  pthread_barrier_init: {
    parameters: ["pointer","pointer","u32"],
    result: "i32",
  },
  // pthread_barrier_destroy @ /usr/include/pthread.h:1260:12
  pthread_barrier_destroy: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_barrier_wait @ /usr/include/pthread.h:1264:12
  pthread_barrier_wait: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_barrierattr_init @ /usr/include/pthread.h:1269:12
  pthread_barrierattr_init: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_barrierattr_destroy @ /usr/include/pthread.h:1273:12
  pthread_barrierattr_destroy: {
    parameters: ["pointer"],
    result: "i32",
  },
  // pthread_barrierattr_getpshared @ /usr/include/pthread.h:1277:12
  pthread_barrierattr_getpshared: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_barrierattr_setpshared @ /usr/include/pthread.h:1283:12
  pthread_barrierattr_setpshared: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // pthread_key_create @ /usr/include/pthread.h:1297:12
  pthread_key_create: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // pthread_key_delete @ /usr/include/pthread.h:1302:12
  pthread_key_delete: {
    parameters: ["u32"],
    result: "i32",
  },
  // pthread_getspecific @ /usr/include/pthread.h:1305:14
  pthread_getspecific: {
    parameters: ["u32"],
    result: "pointer",
  },
  // pthread_setspecific @ /usr/include/pthread.h:1308:12
  pthread_setspecific: {
    parameters: ["u32","pointer"],
    result: "i32",
  },
  // pthread_getcpuclockid @ /usr/include/pthread.h:1315:12
  pthread_getcpuclockid: {
    parameters: ["u64","pointer"],
    result: "i32",
  },
  // pthread_atfork @ /usr/include/pthread.h:1332:12
  pthread_atfork: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // ma_version @ ./miniaudio.h:4449:13
  ma_version: {
    parameters: ["pointer","pointer","pointer"],
    result: "void",
  },
  // ma_version_string @ ./miniaudio.h:4454:20
  ma_version_string: {
    parameters: [],
    result: "pointer",
  },
  // ma_log_callback_init @ ./miniaudio.h:4510:24
  ma_log_callback_init: {
    parameters: ["pointer","pointer"],
    result: "[object Object]",
  },
  // ma_log_uninit @ ./miniaudio.h:4524:13
  ma_log_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_biquad_uninit @ ./miniaudio.h:4577:13
  ma_biquad_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_biquad_get_latency @ ./miniaudio.h:4581:18
  ma_biquad_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_lpf1_uninit @ ./miniaudio.h:4616:13
  ma_lpf1_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_lpf1_get_latency @ ./miniaudio.h:4620:18
  ma_lpf1_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_lpf2_uninit @ ./miniaudio.h:4630:13
  ma_lpf2_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_lpf2_get_latency @ ./miniaudio.h:4634:18
  ma_lpf2_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_lpf_uninit @ ./miniaudio.h:4666:13
  ma_lpf_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_lpf_get_latency @ ./miniaudio.h:4670:18
  ma_lpf_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_hpf1_uninit @ ./miniaudio.h:4705:13
  ma_hpf1_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_hpf1_get_latency @ ./miniaudio.h:4708:18
  ma_hpf1_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_hpf2_uninit @ ./miniaudio.h:4718:13
  ma_hpf2_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_hpf2_get_latency @ ./miniaudio.h:4721:18
  ma_hpf2_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_hpf_uninit @ ./miniaudio.h:4753:13
  ma_hpf_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_hpf_get_latency @ ./miniaudio.h:4756:18
  ma_hpf_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_bpf2_uninit @ ./miniaudio.h:4783:13
  ma_bpf2_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_bpf2_get_latency @ ./miniaudio.h:4786:18
  ma_bpf2_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_bpf_uninit @ ./miniaudio.h:4815:13
  ma_bpf_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_bpf_get_latency @ ./miniaudio.h:4818:18
  ma_bpf_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_notch2_uninit @ ./miniaudio.h:4845:13
  ma_notch2_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_notch2_get_latency @ ./miniaudio.h:4848:18
  ma_notch2_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_peak2_uninit @ ./miniaudio.h:4876:13
  ma_peak2_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_peak2_get_latency @ ./miniaudio.h:4879:18
  ma_peak2_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_loshelf2_uninit @ ./miniaudio.h:4907:13
  ma_loshelf2_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_loshelf2_get_latency @ ./miniaudio.h:4910:18
  ma_loshelf2_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_hishelf2_uninit @ ./miniaudio.h:4938:13
  ma_hishelf2_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_hishelf2_get_latency @ ./miniaudio.h:4941:18
  ma_hishelf2_get_latency: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_delay_config_init @ ./miniaudio.h:4959:24
  ma_delay_config_init: {
    parameters: ["u32","u32","u32","f32"],
    result: "[object Object]",
  },
  // ma_delay_uninit @ ./miniaudio.h:4971:13
  ma_delay_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_delay_set_wet @ ./miniaudio.h:4973:13
  ma_delay_set_wet: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_delay_get_wet @ ./miniaudio.h:4974:14
  ma_delay_get_wet: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_delay_set_dry @ ./miniaudio.h:4975:13
  ma_delay_set_dry: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_delay_get_dry @ ./miniaudio.h:4976:14
  ma_delay_get_dry: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_delay_set_decay @ ./miniaudio.h:4977:13
  ma_delay_set_decay: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_delay_get_decay @ ./miniaudio.h:4978:14
  ma_delay_get_decay: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_gainer_config_init @ ./miniaudio.h:4988:25
  ma_gainer_config_init: {
    parameters: ["u32","u32"],
    result: "[object Object]",
  },
  // ma_gainer_uninit @ ./miniaudio.h:5007:13
  ma_gainer_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_panner_set_pan @ ./miniaudio.h:5046:13
  ma_panner_set_pan: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_panner_get_pan @ ./miniaudio.h:5047:14
  ma_panner_get_pan: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_fader_get_data_format @ ./miniaudio.h:5072:13
  ma_fader_get_data_format: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "void",
  },
  // ma_fader_get_current_volume @ ./miniaudio.h:5075:14
  ma_fader_get_current_volume: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_spatializer_listener_uninit @ ./miniaudio.h:5145:13
  ma_spatializer_listener_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_spatializer_listener_get_channel_map @ ./miniaudio.h:5146:20
  ma_spatializer_listener_get_channel_map: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_spatializer_listener_set_cone @ ./miniaudio.h:5147:13
  ma_spatializer_listener_set_cone: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_spatializer_listener_get_cone @ ./miniaudio.h:5148:13
  ma_spatializer_listener_get_cone: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "void",
  },
  // ma_spatializer_listener_set_position @ ./miniaudio.h:5149:13
  ma_spatializer_listener_set_position: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_spatializer_listener_get_position @ ./miniaudio.h:5150:17
  ma_spatializer_listener_get_position: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_spatializer_listener_set_direction @ ./miniaudio.h:5151:13
  ma_spatializer_listener_set_direction: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_spatializer_listener_get_direction @ ./miniaudio.h:5152:17
  ma_spatializer_listener_get_direction: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_spatializer_listener_set_velocity @ ./miniaudio.h:5153:13
  ma_spatializer_listener_set_velocity: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_spatializer_listener_get_velocity @ ./miniaudio.h:5154:17
  ma_spatializer_listener_get_velocity: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_spatializer_listener_set_speed_of_sound @ ./miniaudio.h:5155:13
  ma_spatializer_listener_set_speed_of_sound: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_spatializer_listener_get_speed_of_sound @ ./miniaudio.h:5156:14
  ma_spatializer_listener_get_speed_of_sound: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_spatializer_listener_set_world_up @ ./miniaudio.h:5157:13
  ma_spatializer_listener_set_world_up: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_spatializer_listener_get_world_up @ ./miniaudio.h:5158:17
  ma_spatializer_listener_get_world_up: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_spatializer_listener_set_enabled @ ./miniaudio.h:5159:13
  ma_spatializer_listener_set_enabled: {
    parameters: ["pointer","u32"],
    result: "void",
  },
  // ma_spatializer_listener_is_enabled @ ./miniaudio.h:5160:18
  ma_spatializer_listener_is_enabled: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_spatializer_uninit @ ./miniaudio.h:5223:13
  ma_spatializer_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_spatializer_get_input_channels @ ./miniaudio.h:5227:18
  ma_spatializer_get_input_channels: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_spatializer_get_output_channels @ ./miniaudio.h:5228:18
  ma_spatializer_get_output_channels: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_spatializer_set_rolloff @ ./miniaudio.h:5233:13
  ma_spatializer_set_rolloff: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_spatializer_get_rolloff @ ./miniaudio.h:5234:14
  ma_spatializer_get_rolloff: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_spatializer_set_min_gain @ ./miniaudio.h:5235:13
  ma_spatializer_set_min_gain: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_spatializer_get_min_gain @ ./miniaudio.h:5236:14
  ma_spatializer_get_min_gain: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_spatializer_set_max_gain @ ./miniaudio.h:5237:13
  ma_spatializer_set_max_gain: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_spatializer_get_max_gain @ ./miniaudio.h:5238:14
  ma_spatializer_get_max_gain: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_spatializer_set_min_distance @ ./miniaudio.h:5239:13
  ma_spatializer_set_min_distance: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_spatializer_get_min_distance @ ./miniaudio.h:5240:14
  ma_spatializer_get_min_distance: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_spatializer_set_max_distance @ ./miniaudio.h:5241:13
  ma_spatializer_set_max_distance: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_spatializer_get_max_distance @ ./miniaudio.h:5242:14
  ma_spatializer_get_max_distance: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_spatializer_set_cone @ ./miniaudio.h:5243:13
  ma_spatializer_set_cone: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_spatializer_get_cone @ ./miniaudio.h:5244:13
  ma_spatializer_get_cone: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "void",
  },
  // ma_spatializer_set_doppler_factor @ ./miniaudio.h:5245:13
  ma_spatializer_set_doppler_factor: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_spatializer_get_doppler_factor @ ./miniaudio.h:5246:14
  ma_spatializer_get_doppler_factor: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_spatializer_set_directional_attenuation_factor @ ./miniaudio.h:5247:13
  ma_spatializer_set_directional_attenuation_factor: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_spatializer_get_directional_attenuation_factor @ ./miniaudio.h:5248:14
  ma_spatializer_get_directional_attenuation_factor: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_spatializer_set_position @ ./miniaudio.h:5249:13
  ma_spatializer_set_position: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_spatializer_get_position @ ./miniaudio.h:5250:17
  ma_spatializer_get_position: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_spatializer_set_direction @ ./miniaudio.h:5251:13
  ma_spatializer_set_direction: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_spatializer_get_direction @ ./miniaudio.h:5252:17
  ma_spatializer_get_direction: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_spatializer_set_velocity @ ./miniaudio.h:5253:13
  ma_spatializer_set_velocity: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_spatializer_get_velocity @ ./miniaudio.h:5254:17
  ma_spatializer_get_velocity: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_spatializer_get_relative_position_and_direction @ ./miniaudio.h:5255:13
  ma_spatializer_get_relative_position_and_direction: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "void",
  },
  // ma_linear_resampler_uninit @ ./miniaudio.h:5314:13
  ma_linear_resampler_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_resampler_uninit @ ./miniaudio.h:5395:13
  ma_resampler_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_channel_converter_uninit @ ./miniaudio.h:5526:13
  ma_channel_converter_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_data_converter_uninit @ ./miniaudio.h:5595:13
  ma_data_converter_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_channel_map_get_channel @ ./miniaudio.h:5662:19
  ma_channel_map_get_channel: {
    parameters: ["pointer","u32","u32"],
    result: "u8",
  },
  // ma_channel_map_init_blank @ ./miniaudio.h:5669:13
  ma_channel_map_init_blank: {
    parameters: ["pointer","u32"],
    result: "void",
  },
  // ma_channel_map_copy @ ./miniaudio.h:5683:13
  ma_channel_map_copy: {
    parameters: ["pointer","pointer","u32"],
    result: "void",
  },
  // ma_channel_map_copy_or_default @ ./miniaudio.h:5690:13
  ma_channel_map_copy_or_default: {
    parameters: ["pointer","u64","pointer","u32"],
    result: "void",
  },
  // ma_channel_map_is_valid @ ./miniaudio.h:5705:18
  ma_channel_map_is_valid: {
    parameters: ["pointer","u32"],
    result: "u32",
  },
  // ma_channel_map_is_equal @ ./miniaudio.h:5714:18
  ma_channel_map_is_equal: {
    parameters: ["pointer","pointer","u32"],
    result: "u32",
  },
  // ma_channel_map_is_blank @ ./miniaudio.h:5721:18
  ma_channel_map_is_blank: {
    parameters: ["pointer","u32"],
    result: "u32",
  },
  // ma_channel_map_contains_channel_position @ ./miniaudio.h:5728:18
  ma_channel_map_contains_channel_position: {
    parameters: ["u32","pointer","u8"],
    result: "u32",
  },
  // ma_channel_map_find_channel_position @ ./miniaudio.h:5736:18
  ma_channel_map_find_channel_position: {
    parameters: ["u32","pointer","u8","pointer"],
    result: "u32",
  },
  // ma_channel_map_to_string @ ./miniaudio.h:5745:15
  ma_channel_map_to_string: {
    parameters: ["pointer","u32","pointer","u64"],
    result: "u64",
  },
  // ma_channel_position_to_string @ ./miniaudio.h:5750:20
  ma_channel_position_to_string: {
    parameters: ["u8"],
    result: "pointer",
  },
  // ma_data_source_config_init @ ./miniaudio.h:5799:30
  ma_data_source_config_init: {
    parameters: [],
    result: "[object Object]",
  },
  // ma_data_source_uninit @ ./miniaudio.h:5816:13
  ma_data_source_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_data_source_is_looping @ ./miniaudio.h:5826:18
  ma_data_source_is_looping: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_data_source_get_range_in_pcm_frames @ ./miniaudio.h:5828:13
  ma_data_source_get_range_in_pcm_frames: {
    parameters: ["pointer","pointer","pointer"],
    result: "void",
  },
  // ma_data_source_get_loop_point_in_pcm_frames @ ./miniaudio.h:5830:13
  ma_data_source_get_loop_point_in_pcm_frames: {
    parameters: ["pointer","pointer","pointer"],
    result: "void",
  },
  // ma_data_source_get_current @ ./miniaudio.h:5832:24
  ma_data_source_get_current: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_data_source_get_next @ ./miniaudio.h:5834:24
  ma_data_source_get_next: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_data_source_get_next_callback @ ./miniaudio.h:5836:37
  ma_data_source_get_next_callback: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_audio_buffer_ref_uninit @ ./miniaudio.h:5851:13
  ma_audio_buffer_ref_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_audio_buffer_ref_at_end @ ./miniaudio.h:5857:18
  ma_audio_buffer_ref_at_end: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_audio_buffer_uninit @ ./miniaudio.h:5887:13
  ma_audio_buffer_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_audio_buffer_uninit_and_free @ ./miniaudio.h:5888:13
  ma_audio_buffer_uninit_and_free: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_audio_buffer_at_end @ ./miniaudio.h:5893:18
  ma_audio_buffer_at_end: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_paged_audio_buffer_data_uninit @ ./miniaudio.h:5927:13
  ma_paged_audio_buffer_data_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_paged_audio_buffer_data_get_head @ ./miniaudio.h:5928:36
  ma_paged_audio_buffer_data_get_head: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_paged_audio_buffer_data_get_tail @ ./miniaudio.h:5929:36
  ma_paged_audio_buffer_data_get_tail: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_paged_audio_buffer_config_init @ ./miniaudio.h:5942:37
  ma_paged_audio_buffer_config_init: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_paged_audio_buffer_uninit @ ./miniaudio.h:5955:13
  ma_paged_audio_buffer_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_rb_uninit @ ./miniaudio.h:5983:13
  ma_rb_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_rb_reset @ ./miniaudio.h:5984:13
  ma_rb_reset: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_rb_pointer_distance @ ./miniaudio.h:5991:17
  ma_rb_pointer_distance: {
    parameters: ["pointer"],
    result: "i32",
  },
  // ma_rb_available_read @ ./miniaudio.h:5992:18
  ma_rb_available_read: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_rb_available_write @ ./miniaudio.h:5993:18
  ma_rb_available_write: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_rb_get_subbuffer_size @ ./miniaudio.h:5994:15
  ma_rb_get_subbuffer_size: {
    parameters: ["pointer"],
    result: "u64",
  },
  // ma_rb_get_subbuffer_stride @ ./miniaudio.h:5995:15
  ma_rb_get_subbuffer_stride: {
    parameters: ["pointer"],
    result: "u64",
  },
  // ma_rb_get_subbuffer_offset @ ./miniaudio.h:5996:15
  ma_rb_get_subbuffer_offset: {
    parameters: ["pointer","u64"],
    result: "u64",
  },
  // ma_rb_get_subbuffer_ptr @ ./miniaudio.h:5997:14
  ma_rb_get_subbuffer_ptr: {
    parameters: ["pointer","u64","pointer"],
    result: "pointer",
  },
  // ma_pcm_rb_uninit @ ./miniaudio.h:6011:13
  ma_pcm_rb_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_pcm_rb_reset @ ./miniaudio.h:6012:13
  ma_pcm_rb_reset: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_pcm_rb_pointer_distance @ ./miniaudio.h:6019:17
  ma_pcm_rb_pointer_distance: {
    parameters: ["pointer"],
    result: "i32",
  },
  // ma_pcm_rb_available_read @ ./miniaudio.h:6020:18
  ma_pcm_rb_available_read: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_pcm_rb_available_write @ ./miniaudio.h:6021:18
  ma_pcm_rb_available_write: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_pcm_rb_get_subbuffer_size @ ./miniaudio.h:6022:18
  ma_pcm_rb_get_subbuffer_size: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_pcm_rb_get_subbuffer_stride @ ./miniaudio.h:6023:18
  ma_pcm_rb_get_subbuffer_stride: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_pcm_rb_get_subbuffer_offset @ ./miniaudio.h:6024:18
  ma_pcm_rb_get_subbuffer_offset: {
    parameters: ["pointer","u32"],
    result: "u32",
  },
  // ma_pcm_rb_get_subbuffer_ptr @ ./miniaudio.h:6025:14
  ma_pcm_rb_get_subbuffer_ptr: {
    parameters: ["pointer","u32","pointer"],
    result: "pointer",
  },
  // ma_pcm_rb_get_channels @ ./miniaudio.h:6027:18
  ma_pcm_rb_get_channels: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_pcm_rb_get_sample_rate @ ./miniaudio.h:6028:18
  ma_pcm_rb_get_sample_rate: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_pcm_rb_set_sample_rate @ ./miniaudio.h:6029:13
  ma_pcm_rb_set_sample_rate: {
    parameters: ["pointer","u32"],
    result: "void",
  },
  // ma_malloc @ ./miniaudio.h:6064:14
  ma_malloc: {
    parameters: ["u64","pointer"],
    result: "pointer",
  },
  // ma_calloc @ ./miniaudio.h:6069:14
  ma_calloc: {
    parameters: ["u64","pointer"],
    result: "pointer",
  },
  // ma_realloc @ ./miniaudio.h:6074:14
  ma_realloc: {
    parameters: ["pointer","u64","pointer"],
    result: "pointer",
  },
  // ma_free @ ./miniaudio.h:6079:13
  ma_free: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_aligned_malloc @ ./miniaudio.h:6084:14
  ma_aligned_malloc: {
    parameters: ["u64","u64","pointer"],
    result: "pointer",
  },
  // ma_aligned_free @ ./miniaudio.h:6089:13
  ma_aligned_free: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_blend_f32 @ ./miniaudio.h:6099:13
  ma_blend_f32: {
    parameters: ["pointer","pointer","pointer","f32","u32"],
    result: "void",
  },
  // ma_log_level_to_string @ ./miniaudio.h:6115:20
  ma_log_level_to_string: {
    parameters: ["u32"],
    result: "pointer",
  },
  // ma_mutex_uninit @ ./miniaudio.h:6153:13
  ma_mutex_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_mutex_lock @ ./miniaudio.h:6158:13
  ma_mutex_lock: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_mutex_unlock @ ./miniaudio.h:6163:13
  ma_mutex_unlock: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_event_uninit @ ./miniaudio.h:6174:13
  ma_event_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_fence_uninit @ ./miniaudio.h:6211:13
  ma_fence_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_async_notification_poll_is_signalled @ ./miniaudio.h:6243:18
  ma_async_notification_poll_is_signalled: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_slot_allocator_config_init @ ./miniaudio.h:6294:33
  ma_slot_allocator_config_init: {
    parameters: ["u32"],
    result: "[object Object]",
  },
  // ma_slot_allocator_uninit @ ./miniaudio.h:6317:13
  ma_slot_allocator_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_job_init @ ./miniaudio.h:6473:15
  ma_job_init: {
    parameters: ["u16"],
    result: "[object Object]",
  },
  // ma_job_queue_config_init @ ./miniaudio.h:6494:28
  ma_job_queue_config_init: {
    parameters: ["u32","u32"],
    result: "[object Object]",
  },
  // ma_job_queue_uninit @ ./miniaudio.h:6520:13
  ma_job_queue_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_device_job_thread_config_init @ ./miniaudio.h:6696:36
  ma_device_job_thread_config_init: {
    parameters: [],
    result: "[object Object]",
  },
  // ma_device_job_thread_uninit @ ./miniaudio.h:6706:13
  ma_device_job_thread_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_context_config_init @ ./miniaudio.h:8030:26
  ma_context_config_init: {
    parameters: [],
    result: "[object Object]",
  },
  // ma_context_sizeof @ ./miniaudio.h:8274:15
  ma_context_sizeof: {
    parameters: [],
    result: "u64",
  },
  // ma_context_get_log @ ./miniaudio.h:8293:16
  ma_context_get_log: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_context_is_loopback_supported @ ./miniaudio.h:8469:18
  ma_context_is_loopback_supported: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_device_uninit @ ./miniaudio.h:8959:13
  ma_device_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_device_get_context @ ./miniaudio.h:8965:20
  ma_device_get_context: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_device_get_log @ ./miniaudio.h:8970:16
  ma_device_get_log: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_device_is_started @ ./miniaudio.h:9182:18
  ma_device_is_started: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_calculate_buffer_size_in_milliseconds_from_frames @ ./miniaudio.h:9679:18
  ma_calculate_buffer_size_in_milliseconds_from_frames: {
    parameters: ["u32","u32"],
    result: "u32",
  },
  // ma_calculate_buffer_size_in_frames_from_milliseconds @ ./miniaudio.h:9684:18
  ma_calculate_buffer_size_in_frames_from_milliseconds: {
    parameters: ["u32","u32"],
    result: "u32",
  },
  // ma_volume_linear_to_db @ ./miniaudio.h:9766:14
  ma_volume_linear_to_db: {
    parameters: ["f32"],
    result: "f32",
  },
  // ma_volume_db_to_linear @ ./miniaudio.h:9771:14
  ma_volume_db_to_linear: {
    parameters: ["f32"],
    result: "f32",
  },
  // ma_encoder_uninit @ ./miniaudio.h:10082:13
  ma_encoder_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_waveform_uninit @ ./miniaudio.h:10123:13
  ma_waveform_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_pulsewave_uninit @ ./miniaudio.h:10150:13
  ma_pulsewave_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_noise_uninit @ ./miniaudio.h:10205:13
  ma_noise_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_resource_manager_pipeline_notifications_init @ ./miniaudio.h:10257:51
  ma_resource_manager_pipeline_notifications_init: {
    parameters: [],
    result: "[object Object]",
  },
  // ma_resource_manager_uninit @ ./miniaudio.h:10459:13
  ma_resource_manager_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_resource_manager_get_log @ ./miniaudio.h:10460:16
  ma_resource_manager_get_log: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_resource_manager_data_buffer_is_looping @ ./miniaudio.h:10487:18
  ma_resource_manager_data_buffer_is_looping: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_resource_manager_data_stream_is_looping @ ./miniaudio.h:10502:18
  ma_resource_manager_data_stream_is_looping: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_resource_manager_data_source_is_looping @ ./miniaudio.h:10518:18
  ma_resource_manager_data_source_is_looping: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_node_uninit @ ./miniaudio.h:10703:13
  ma_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_node_get_node_graph @ ./miniaudio.h:10704:23
  ma_node_get_node_graph: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_node_get_input_bus_count @ ./miniaudio.h:10705:18
  ma_node_get_input_bus_count: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_node_get_output_bus_count @ ./miniaudio.h:10706:18
  ma_node_get_output_bus_count: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_node_get_input_channels @ ./miniaudio.h:10707:18
  ma_node_get_input_channels: {
    parameters: ["pointer","u32"],
    result: "u32",
  },
  // ma_node_get_output_channels @ ./miniaudio.h:10708:18
  ma_node_get_output_channels: {
    parameters: ["pointer","u32"],
    result: "u32",
  },
  // ma_node_get_output_bus_volume @ ./miniaudio.h:10713:14
  ma_node_get_output_bus_volume: {
    parameters: ["pointer","u32"],
    result: "f32",
  },
  // ma_node_graph_config_init @ ./miniaudio.h:10730:29
  ma_node_graph_config_init: {
    parameters: ["u32"],
    result: "[object Object]",
  },
  // ma_node_graph_uninit @ ./miniaudio.h:10745:13
  ma_node_graph_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_node_graph_get_endpoint @ ./miniaudio.h:10746:17
  ma_node_graph_get_endpoint: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_node_graph_get_channels @ ./miniaudio.h:10748:18
  ma_node_graph_get_channels: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_data_source_node_uninit @ ./miniaudio.h:10771:13
  ma_data_source_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_data_source_node_is_looping @ ./miniaudio.h:10773:18
  ma_data_source_node_is_looping: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_splitter_node_uninit @ ./miniaudio.h:10793:13
  ma_splitter_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_biquad_node_uninit @ ./miniaudio.h:10816:13
  ma_biquad_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_lpf_node_uninit @ ./miniaudio.h:10839:13
  ma_lpf_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_hpf_node_uninit @ ./miniaudio.h:10862:13
  ma_hpf_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_bpf_node_uninit @ ./miniaudio.h:10885:13
  ma_bpf_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_notch_node_uninit @ ./miniaudio.h:10908:13
  ma_notch_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_peak_node_uninit @ ./miniaudio.h:10931:13
  ma_peak_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_loshelf_node_uninit @ ./miniaudio.h:10954:13
  ma_loshelf_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_hishelf_node_uninit @ ./miniaudio.h:10977:13
  ma_hishelf_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_delay_node_uninit @ ./miniaudio.h:10996:13
  ma_delay_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_delay_node_set_wet @ ./miniaudio.h:10997:13
  ma_delay_node_set_wet: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_delay_node_get_wet @ ./miniaudio.h:10998:14
  ma_delay_node_get_wet: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_delay_node_set_dry @ ./miniaudio.h:10999:13
  ma_delay_node_set_dry: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_delay_node_get_dry @ ./miniaudio.h:11000:14
  ma_delay_node_get_dry: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_delay_node_set_decay @ ./miniaudio.h:11001:13
  ma_delay_node_set_decay: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_delay_node_get_decay @ ./miniaudio.h:11002:14
  ma_delay_node_get_decay: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_engine_node_uninit @ ./miniaudio.h:11100:13
  ma_engine_node_uninit: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // ma_engine_uninit @ ./miniaudio.h:11234:13
  ma_engine_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_engine_get_node_graph @ ./miniaudio.h:11236:23
  ma_engine_get_node_graph: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_engine_get_resource_manager @ ./miniaudio.h:11238:29
  ma_engine_get_resource_manager: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_engine_get_device @ ./miniaudio.h:11240:19
  ma_engine_get_device: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_engine_get_log @ ./miniaudio.h:11241:16
  ma_engine_get_log: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_engine_get_endpoint @ ./miniaudio.h:11242:17
  ma_engine_get_endpoint: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_engine_get_channels @ ./miniaudio.h:11249:18
  ma_engine_get_channels: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_engine_get_sample_rate @ ./miniaudio.h:11250:18
  ma_engine_get_sample_rate: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_engine_get_volume @ ./miniaudio.h:11255:14
  ma_engine_get_volume: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_engine_get_gain_db @ ./miniaudio.h:11257:14
  ma_engine_get_gain_db: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_engine_get_listener_count @ ./miniaudio.h:11259:18
  ma_engine_get_listener_count: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_engine_find_closest_listener @ ./miniaudio.h:11260:18
  ma_engine_find_closest_listener: {
    parameters: ["pointer","f32","f32","f32"],
    result: "u32",
  },
  // ma_engine_listener_set_position @ ./miniaudio.h:11261:13
  ma_engine_listener_set_position: {
    parameters: ["pointer","u32","f32","f32","f32"],
    result: "void",
  },
  // ma_engine_listener_get_position @ ./miniaudio.h:11262:17
  ma_engine_listener_get_position: {
    parameters: ["pointer","u32"],
    result: "[object Object]",
  },
  // ma_engine_listener_set_direction @ ./miniaudio.h:11263:13
  ma_engine_listener_set_direction: {
    parameters: ["pointer","u32","f32","f32","f32"],
    result: "void",
  },
  // ma_engine_listener_get_direction @ ./miniaudio.h:11264:17
  ma_engine_listener_get_direction: {
    parameters: ["pointer","u32"],
    result: "[object Object]",
  },
  // ma_engine_listener_set_velocity @ ./miniaudio.h:11265:13
  ma_engine_listener_set_velocity: {
    parameters: ["pointer","u32","f32","f32","f32"],
    result: "void",
  },
  // ma_engine_listener_get_velocity @ ./miniaudio.h:11266:17
  ma_engine_listener_get_velocity: {
    parameters: ["pointer","u32"],
    result: "[object Object]",
  },
  // ma_engine_listener_set_cone @ ./miniaudio.h:11267:13
  ma_engine_listener_set_cone: {
    parameters: ["pointer","u32","f32","f32","f32"],
    result: "void",
  },
  // ma_engine_listener_get_cone @ ./miniaudio.h:11268:13
  ma_engine_listener_get_cone: {
    parameters: ["pointer","u32","pointer","pointer","pointer"],
    result: "void",
  },
  // ma_engine_listener_set_world_up @ ./miniaudio.h:11269:13
  ma_engine_listener_set_world_up: {
    parameters: ["pointer","u32","f32","f32","f32"],
    result: "void",
  },
  // ma_engine_listener_get_world_up @ ./miniaudio.h:11270:17
  ma_engine_listener_get_world_up: {
    parameters: ["pointer","u32"],
    result: "[object Object]",
  },
  // ma_engine_listener_set_enabled @ ./miniaudio.h:11271:13
  ma_engine_listener_set_enabled: {
    parameters: ["pointer","u32","u32"],
    result: "void",
  },
  // ma_engine_listener_is_enabled @ ./miniaudio.h:11272:18
  ma_engine_listener_is_enabled: {
    parameters: ["pointer","u32"],
    result: "u32",
  },
  // ma_sound_uninit @ ./miniaudio.h:11286:13
  ma_sound_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_sound_get_engine @ ./miniaudio.h:11287:19
  ma_sound_get_engine: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_sound_get_data_source @ ./miniaudio.h:11288:24
  ma_sound_get_data_source: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_sound_set_volume @ ./miniaudio.h:11293:13
  ma_sound_set_volume: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_get_volume @ ./miniaudio.h:11294:14
  ma_sound_get_volume: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_set_pan @ ./miniaudio.h:11295:13
  ma_sound_set_pan: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_get_pan @ ./miniaudio.h:11296:14
  ma_sound_get_pan: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_set_pitch @ ./miniaudio.h:11299:13
  ma_sound_set_pitch: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_get_pitch @ ./miniaudio.h:11300:14
  ma_sound_get_pitch: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_set_spatialization_enabled @ ./miniaudio.h:11301:13
  ma_sound_set_spatialization_enabled: {
    parameters: ["pointer","u32"],
    result: "void",
  },
  // ma_sound_is_spatialization_enabled @ ./miniaudio.h:11302:18
  ma_sound_is_spatialization_enabled: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_sound_set_pinned_listener_index @ ./miniaudio.h:11303:13
  ma_sound_set_pinned_listener_index: {
    parameters: ["pointer","u32"],
    result: "void",
  },
  // ma_sound_get_pinned_listener_index @ ./miniaudio.h:11304:18
  ma_sound_get_pinned_listener_index: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_sound_get_listener_index @ ./miniaudio.h:11305:18
  ma_sound_get_listener_index: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_sound_get_direction_to_listener @ ./miniaudio.h:11306:17
  ma_sound_get_direction_to_listener: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_sound_set_position @ ./miniaudio.h:11307:13
  ma_sound_set_position: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_sound_get_position @ ./miniaudio.h:11308:17
  ma_sound_get_position: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_sound_set_direction @ ./miniaudio.h:11309:13
  ma_sound_set_direction: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_sound_get_direction @ ./miniaudio.h:11310:17
  ma_sound_get_direction: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_sound_set_velocity @ ./miniaudio.h:11311:13
  ma_sound_set_velocity: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_sound_get_velocity @ ./miniaudio.h:11312:17
  ma_sound_get_velocity: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_sound_set_rolloff @ ./miniaudio.h:11317:13
  ma_sound_set_rolloff: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_get_rolloff @ ./miniaudio.h:11318:14
  ma_sound_get_rolloff: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_set_min_gain @ ./miniaudio.h:11319:13
  ma_sound_set_min_gain: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_get_min_gain @ ./miniaudio.h:11320:14
  ma_sound_get_min_gain: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_set_max_gain @ ./miniaudio.h:11321:13
  ma_sound_set_max_gain: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_get_max_gain @ ./miniaudio.h:11322:14
  ma_sound_get_max_gain: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_set_min_distance @ ./miniaudio.h:11323:13
  ma_sound_set_min_distance: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_get_min_distance @ ./miniaudio.h:11324:14
  ma_sound_get_min_distance: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_set_max_distance @ ./miniaudio.h:11325:13
  ma_sound_set_max_distance: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_get_max_distance @ ./miniaudio.h:11326:14
  ma_sound_get_max_distance: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_set_cone @ ./miniaudio.h:11327:13
  ma_sound_set_cone: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_sound_get_cone @ ./miniaudio.h:11328:13
  ma_sound_get_cone: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "void",
  },
  // ma_sound_set_doppler_factor @ ./miniaudio.h:11329:13
  ma_sound_set_doppler_factor: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_get_doppler_factor @ ./miniaudio.h:11330:14
  ma_sound_get_doppler_factor: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_set_directional_attenuation_factor @ ./miniaudio.h:11331:13
  ma_sound_set_directional_attenuation_factor: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_get_directional_attenuation_factor @ ./miniaudio.h:11332:14
  ma_sound_get_directional_attenuation_factor: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_get_current_fade_volume @ ./miniaudio.h:11337:14
  ma_sound_get_current_fade_volume: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_is_playing @ ./miniaudio.h:11344:18
  ma_sound_is_playing: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_sound_set_looping @ ./miniaudio.h:11347:13
  ma_sound_set_looping: {
    parameters: ["pointer","u32"],
    result: "void",
  },
  // ma_sound_is_looping @ ./miniaudio.h:11348:18
  ma_sound_is_looping: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_sound_at_end @ ./miniaudio.h:11349:18
  ma_sound_at_end: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_sound_group_uninit @ ./miniaudio.h:11360:13
  ma_sound_group_uninit: {
    parameters: ["pointer"],
    result: "void",
  },
  // ma_sound_group_get_engine @ ./miniaudio.h:11361:19
  ma_sound_group_get_engine: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // ma_sound_group_set_volume @ ./miniaudio.h:11364:13
  ma_sound_group_set_volume: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_group_get_volume @ ./miniaudio.h:11365:14
  ma_sound_group_get_volume: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_set_pan @ ./miniaudio.h:11366:13
  ma_sound_group_set_pan: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_group_get_pan @ ./miniaudio.h:11367:14
  ma_sound_group_get_pan: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_set_pitch @ ./miniaudio.h:11370:13
  ma_sound_group_set_pitch: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_group_get_pitch @ ./miniaudio.h:11371:14
  ma_sound_group_get_pitch: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_set_spatialization_enabled @ ./miniaudio.h:11372:13
  ma_sound_group_set_spatialization_enabled: {
    parameters: ["pointer","u32"],
    result: "void",
  },
  // ma_sound_group_is_spatialization_enabled @ ./miniaudio.h:11373:18
  ma_sound_group_is_spatialization_enabled: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_sound_group_set_pinned_listener_index @ ./miniaudio.h:11374:13
  ma_sound_group_set_pinned_listener_index: {
    parameters: ["pointer","u32"],
    result: "void",
  },
  // ma_sound_group_get_pinned_listener_index @ ./miniaudio.h:11375:18
  ma_sound_group_get_pinned_listener_index: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_sound_group_get_listener_index @ ./miniaudio.h:11376:18
  ma_sound_group_get_listener_index: {
    parameters: ["pointer"],
    result: "u32",
  },
  // ma_sound_group_get_direction_to_listener @ ./miniaudio.h:11377:17
  ma_sound_group_get_direction_to_listener: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_sound_group_set_position @ ./miniaudio.h:11378:13
  ma_sound_group_set_position: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_sound_group_get_position @ ./miniaudio.h:11379:17
  ma_sound_group_get_position: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_sound_group_set_direction @ ./miniaudio.h:11380:13
  ma_sound_group_set_direction: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_sound_group_get_direction @ ./miniaudio.h:11381:17
  ma_sound_group_get_direction: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_sound_group_set_velocity @ ./miniaudio.h:11382:13
  ma_sound_group_set_velocity: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_sound_group_get_velocity @ ./miniaudio.h:11383:17
  ma_sound_group_get_velocity: {
    parameters: ["pointer"],
    result: "[object Object]",
  },
  // ma_sound_group_set_rolloff @ ./miniaudio.h:11388:13
  ma_sound_group_set_rolloff: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_group_get_rolloff @ ./miniaudio.h:11389:14
  ma_sound_group_get_rolloff: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_set_min_gain @ ./miniaudio.h:11390:13
  ma_sound_group_set_min_gain: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_group_get_min_gain @ ./miniaudio.h:11391:14
  ma_sound_group_get_min_gain: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_set_max_gain @ ./miniaudio.h:11392:13
  ma_sound_group_set_max_gain: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_group_get_max_gain @ ./miniaudio.h:11393:14
  ma_sound_group_get_max_gain: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_set_min_distance @ ./miniaudio.h:11394:13
  ma_sound_group_set_min_distance: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_group_get_min_distance @ ./miniaudio.h:11395:14
  ma_sound_group_get_min_distance: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_set_max_distance @ ./miniaudio.h:11396:13
  ma_sound_group_set_max_distance: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_group_get_max_distance @ ./miniaudio.h:11397:14
  ma_sound_group_get_max_distance: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_set_cone @ ./miniaudio.h:11398:13
  ma_sound_group_set_cone: {
    parameters: ["pointer","f32","f32","f32"],
    result: "void",
  },
  // ma_sound_group_get_cone @ ./miniaudio.h:11399:13
  ma_sound_group_get_cone: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "void",
  },
  // ma_sound_group_set_doppler_factor @ ./miniaudio.h:11400:13
  ma_sound_group_set_doppler_factor: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_group_get_doppler_factor @ ./miniaudio.h:11401:14
  ma_sound_group_get_doppler_factor: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_set_directional_attenuation_factor @ ./miniaudio.h:11402:13
  ma_sound_group_set_directional_attenuation_factor: {
    parameters: ["pointer","f32"],
    result: "void",
  },
  // ma_sound_group_get_directional_attenuation_factor @ ./miniaudio.h:11403:14
  ma_sound_group_get_directional_attenuation_factor: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_get_current_fade_volume @ ./miniaudio.h:11406:14
  ma_sound_group_get_current_fade_volume: {
    parameters: ["pointer"],
    result: "f32",
  },
  // ma_sound_group_is_playing @ ./miniaudio.h:11411:18
  ma_sound_group_is_playing: {
    parameters: ["pointer"],
    result: "u32",
  }
} as const;

const { symbols } = Deno.dlopen("libminiaudio.so", _);

export default symbols;

