// Generated by littledivy/ffigen
const _ = {
  // select @ /usr/include/sys/select.h:102:12
  select: {
    parameters: ["i32","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // pselect @ /usr/include/sys/select.h:127:12
  pselect: {
    parameters: ["i32","pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // _Xmblen @ include/Xlib.h:63:1
  _Xmblen: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XLoadQueryFont @ include/Xlib.h:1394:21
  XLoadQueryFont: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // XQueryFont @ include/Xlib.h:1399:21
  XQueryFont: {
    parameters: ["pointer","u64"],
    result: "pointer",
  },
  // XGetMotionEvents @ include/Xlib.h:1405:20
  XGetMotionEvents: {
    parameters: ["pointer","u64","u64","u64","pointer"],
    result: "pointer",
  },
  // XDeleteModifiermapEntry @ include/Xlib.h:1413:25
  XDeleteModifiermapEntry: {
    parameters: ["pointer","u8","i32"],
    result: "pointer",
  },
  // XGetModifierMapping @ include/Xlib.h:1423:25
  XGetModifierMapping: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XInsertModifiermapEntry @ include/Xlib.h:1427:25
  XInsertModifiermapEntry: {
    parameters: ["pointer","u8","i32"],
    result: "pointer",
  },
  // XNewModifiermap @ include/Xlib.h:1437:25
  XNewModifiermap: {
    parameters: ["i32"],
    result: "pointer",
  },
  // XCreateImage @ include/Xlib.h:1441:16
  XCreateImage: {
    parameters: ["pointer","pointer","u32","i32","i32","pointer","u32","u32","i32","i32"],
    result: "pointer",
  },
  // XInitImage @ include/Xlib.h:1453:15
  XInitImage: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XGetImage @ include/Xlib.h:1456:16
  XGetImage: {
    parameters: ["pointer","u64","i32","i32","u32","u32","u64","i32"],
    result: "pointer",
  },
  // XGetSubImage @ include/Xlib.h:1466:16
  XGetSubImage: {
    parameters: ["pointer","u64","i32","i32","u32","u32","u64","i32","pointer","i32","i32"],
    result: "pointer",
  },
  // XOpenDisplay @ include/Xlib.h:1483:17
  XOpenDisplay: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XrmInitialize @ include/Xlib.h:1487:13
  XrmInitialize: {
    parameters: [],
    result: "void",
  },
  // XFetchBytes @ include/Xlib.h:1491:14
  XFetchBytes: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // XFetchBuffer @ include/Xlib.h:1495:14
  XFetchBuffer: {
    parameters: ["pointer","pointer","i32"],
    result: "pointer",
  },
  // XGetAtomName @ include/Xlib.h:1500:14
  XGetAtomName: {
    parameters: ["pointer","u64"],
    result: "pointer",
  },
  // XGetAtomNames @ include/Xlib.h:1504:15
  XGetAtomNames: {
    parameters: ["pointer","pointer","i32","pointer"],
    result: "i32",
  },
  // XGetDefault @ include/Xlib.h:1510:14
  XGetDefault: {
    parameters: ["pointer","pointer","pointer"],
    result: "pointer",
  },
  // XDisplayName @ include/Xlib.h:1515:14
  XDisplayName: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XKeysymToString @ include/Xlib.h:1518:14
  XKeysymToString: {
    parameters: ["u64"],
    result: "pointer",
  },
  // XSynchronize @ include/Xlib.h:1522:14
  XSynchronize: {
    parameters: ["pointer","i32"],
    result: "pointer",
  },
  // XSetAfterFunction @ include/Xlib.h:1528:14
  XSetAfterFunction: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // XInternAtom @ include/Xlib.h:1536:13
  XInternAtom: {
    parameters: ["pointer","pointer","i32"],
    result: "u64",
  },
  // XInternAtoms @ include/Xlib.h:1541:15
  XInternAtoms: {
    parameters: ["pointer","pointer","i32","i32","pointer"],
    result: "i32",
  },
  // XCopyColormapAndFree @ include/Xlib.h:1548:17
  XCopyColormapAndFree: {
    parameters: ["pointer","u64"],
    result: "u64",
  },
  // XCreateColormap @ include/Xlib.h:1552:17
  XCreateColormap: {
    parameters: ["pointer","u64","pointer","i32"],
    result: "u64",
  },
  // XCreatePixmapCursor @ include/Xlib.h:1558:15
  XCreatePixmapCursor: {
    parameters: ["pointer","u64","u64","pointer","pointer","u32","u32"],
    result: "u64",
  },
  // XCreateGlyphCursor @ include/Xlib.h:1567:15
  XCreateGlyphCursor: {
    parameters: ["pointer","u64","u64","u32","u32","pointer","pointer"],
    result: "u64",
  },
  // XCreateFontCursor @ include/Xlib.h:1576:15
  XCreateFontCursor: {
    parameters: ["pointer","u32"],
    result: "u64",
  },
  // XLoadFont @ include/Xlib.h:1580:13
  XLoadFont: {
    parameters: ["pointer","pointer"],
    result: "u64",
  },
  // XCreateGC @ include/Xlib.h:1584:11
  XCreateGC: {
    parameters: ["pointer","u64","u64","pointer"],
    result: "pointer",
  },
  // XGContextFromGC @ include/Xlib.h:1590:17
  XGContextFromGC: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XFlushGC @ include/Xlib.h:1593:13
  XFlushGC: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // XCreatePixmap @ include/Xlib.h:1597:15
  XCreatePixmap: {
    parameters: ["pointer","u64","u32","u32","u32"],
    result: "u64",
  },
  // XCreateBitmapFromData @ include/Xlib.h:1604:15
  XCreateBitmapFromData: {
    parameters: ["pointer","u64","pointer","u32","u32"],
    result: "u64",
  },
  // XCreatePixmapFromBitmapData @ include/Xlib.h:1611:15
  XCreatePixmapFromBitmapData: {
    parameters: ["pointer","u64","pointer","u32","u32","u64","u64","u32"],
    result: "u64",
  },
  // XCreateSimpleWindow @ include/Xlib.h:1621:15
  XCreateSimpleWindow: {
    parameters: ["pointer","u64","i32","i32","u32","u32","u32","u64","u64"],
    result: "u64",
  },
  // XGetSelectionOwner @ include/Xlib.h:1632:15
  XGetSelectionOwner: {
    parameters: ["pointer","u64"],
    result: "u64",
  },
  // XCreateWindow @ include/Xlib.h:1636:15
  XCreateWindow: {
    parameters: ["pointer","u64","i32","i32","u32","u32","u32","i32","u32","pointer","u64","pointer"],
    result: "u64",
  },
  // XListInstalledColormaps @ include/Xlib.h:1650:18
  XListInstalledColormaps: {
    parameters: ["pointer","u64","pointer"],
    result: "pointer",
  },
  // XListFonts @ include/Xlib.h:1655:15
  XListFonts: {
    parameters: ["pointer","pointer","i32","pointer"],
    result: "pointer",
  },
  // XListFontsWithInfo @ include/Xlib.h:1661:15
  XListFontsWithInfo: {
    parameters: ["pointer","pointer","i32","pointer","pointer"],
    result: "pointer",
  },
  // XGetFontPath @ include/Xlib.h:1668:15
  XGetFontPath: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // XListExtensions @ include/Xlib.h:1672:15
  XListExtensions: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // XListProperties @ include/Xlib.h:1676:14
  XListProperties: {
    parameters: ["pointer","u64","pointer"],
    result: "pointer",
  },
  // XListHosts @ include/Xlib.h:1681:22
  XListHosts: {
    parameters: ["pointer","pointer","pointer"],
    result: "pointer",
  },
  // XKeycodeToKeysym @ include/Xlib.h:1687:15
  XKeycodeToKeysym: {
    parameters: ["pointer","u8","i32"],
    result: "u64",
  },
  // XLookupKeysym @ include/Xlib.h:1696:15
  XLookupKeysym: {
    parameters: ["pointer","i32"],
    result: "u64",
  },
  // XGetKeyboardMapping @ include/Xlib.h:1700:16
  XGetKeyboardMapping: {
    parameters: ["pointer","u8","i32","pointer"],
    result: "pointer",
  },
  // XStringToKeysym @ include/Xlib.h:1710:15
  XStringToKeysym: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XMaxRequestSize @ include/Xlib.h:1713:13
  XMaxRequestSize: {
    parameters: ["pointer"],
    result: "i64",
  },
  // XExtendedMaxRequestSize @ include/Xlib.h:1716:13
  XExtendedMaxRequestSize: {
    parameters: ["pointer"],
    result: "i64",
  },
  // XResourceManagerString @ include/Xlib.h:1719:14
  XResourceManagerString: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XScreenResourceString @ include/Xlib.h:1722:14
  XScreenResourceString: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XDisplayMotionBufferSize @ include/Xlib.h:1725:22
  XDisplayMotionBufferSize: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XVisualIDFromVisual @ include/Xlib.h:1728:17
  XVisualIDFromVisual: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XInitThreads @ include/Xlib.h:1734:15
  XInitThreads: {
    parameters: [],
    result: "i32",
  },
  // XFreeThreads @ include/Xlib.h:1738:15
  XFreeThreads: {
    parameters: [],
    result: "i32",
  },
  // XLockDisplay @ include/Xlib.h:1742:13
  XLockDisplay: {
    parameters: ["pointer"],
    result: "void",
  },
  // XUnlockDisplay @ include/Xlib.h:1746:13
  XUnlockDisplay: {
    parameters: ["pointer"],
    result: "void",
  },
  // XInitExtension @ include/Xlib.h:1752:19
  XInitExtension: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // XAddExtension @ include/Xlib.h:1757:19
  XAddExtension: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XFindOnExtensionList @ include/Xlib.h:1760:18
  XFindOnExtensionList: {
    parameters: ["pointer","i32"],
    result: "pointer",
  },
  // XRootWindow @ include/Xlib.h:1769:15
  XRootWindow: {
    parameters: ["pointer","i32"],
    result: "u64",
  },
  // XDefaultRootWindow @ include/Xlib.h:1773:15
  XDefaultRootWindow: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XRootWindowOfScreen @ include/Xlib.h:1776:15
  XRootWindowOfScreen: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XDefaultVisual @ include/Xlib.h:1779:16
  XDefaultVisual: {
    parameters: ["pointer","i32"],
    result: "pointer",
  },
  // XDefaultVisualOfScreen @ include/Xlib.h:1783:16
  XDefaultVisualOfScreen: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XDefaultGC @ include/Xlib.h:1786:11
  XDefaultGC: {
    parameters: ["pointer","i32"],
    result: "pointer",
  },
  // XDefaultGCOfScreen @ include/Xlib.h:1790:11
  XDefaultGCOfScreen: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XBlackPixel @ include/Xlib.h:1793:22
  XBlackPixel: {
    parameters: ["pointer","i32"],
    result: "u64",
  },
  // XWhitePixel @ include/Xlib.h:1797:22
  XWhitePixel: {
    parameters: ["pointer","i32"],
    result: "u64",
  },
  // XAllPlanes @ include/Xlib.h:1801:22
  XAllPlanes: {
    parameters: [],
    result: "u64",
  },
  // XBlackPixelOfScreen @ include/Xlib.h:1804:22
  XBlackPixelOfScreen: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XWhitePixelOfScreen @ include/Xlib.h:1807:22
  XWhitePixelOfScreen: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XNextRequest @ include/Xlib.h:1810:22
  XNextRequest: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XLastKnownRequestProcessed @ include/Xlib.h:1813:22
  XLastKnownRequestProcessed: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XServerVendor @ include/Xlib.h:1816:14
  XServerVendor: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XDisplayString @ include/Xlib.h:1819:14
  XDisplayString: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XDefaultColormap @ include/Xlib.h:1822:17
  XDefaultColormap: {
    parameters: ["pointer","i32"],
    result: "u64",
  },
  // XDefaultColormapOfScreen @ include/Xlib.h:1826:17
  XDefaultColormapOfScreen: {
    parameters: ["pointer"],
    result: "u64",
  },
  // XDisplayOfScreen @ include/Xlib.h:1829:17
  XDisplayOfScreen: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XScreenOfDisplay @ include/Xlib.h:1832:16
  XScreenOfDisplay: {
    parameters: ["pointer","i32"],
    result: "pointer",
  },
  // XDefaultScreenOfDisplay @ include/Xlib.h:1836:16
  XDefaultScreenOfDisplay: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XEventMaskOfScreen @ include/Xlib.h:1839:13
  XEventMaskOfScreen: {
    parameters: ["pointer"],
    result: "i64",
  },
  // XScreenNumberOfScreen @ include/Xlib.h:1843:12
  XScreenNumberOfScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XSetErrorHandler @ include/Xlib.h:1852:22
  XSetErrorHandler: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XSetIOErrorHandler @ include/Xlib.h:1861:24
  XSetIOErrorHandler: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XSetIOErrorExitHandler @ include/Xlib.h:1870:13
  XSetIOErrorExitHandler: {
    parameters: ["pointer","pointer","pointer"],
    result: "void",
  },
  // XListPixmapFormats @ include/Xlib.h:1876:29
  XListPixmapFormats: {
    parameters: ["pointer","pointer"],
    result: "pointer",
  },
  // XListDepths @ include/Xlib.h:1880:13
  XListDepths: {
    parameters: ["pointer","i32","pointer"],
    result: "pointer",
  },
  // XReconfigureWMWindow @ include/Xlib.h:1888:15
  XReconfigureWMWindow: {
    parameters: ["pointer","u64","i32","u32","pointer"],
    result: "i32",
  },
  // XGetWMProtocols @ include/Xlib.h:1896:15
  XGetWMProtocols: {
    parameters: ["pointer","u64","pointer","pointer"],
    result: "i32",
  },
  // XSetWMProtocols @ include/Xlib.h:1902:15
  XSetWMProtocols: {
    parameters: ["pointer","u64","pointer","i32"],
    result: "i32",
  },
  // XIconifyWindow @ include/Xlib.h:1908:15
  XIconifyWindow: {
    parameters: ["pointer","u64","i32"],
    result: "i32",
  },
  // XWithdrawWindow @ include/Xlib.h:1913:15
  XWithdrawWindow: {
    parameters: ["pointer","u64","i32"],
    result: "i32",
  },
  // XGetCommand @ include/Xlib.h:1918:15
  XGetCommand: {
    parameters: ["pointer","u64","pointer","pointer"],
    result: "i32",
  },
  // XGetWMColormapWindows @ include/Xlib.h:1924:15
  XGetWMColormapWindows: {
    parameters: ["pointer","u64","pointer","pointer"],
    result: "i32",
  },
  // XSetWMColormapWindows @ include/Xlib.h:1930:15
  XSetWMColormapWindows: {
    parameters: ["pointer","u64","pointer","i32"],
    result: "i32",
  },
  // XFreeStringList @ include/Xlib.h:1936:13
  XFreeStringList: {
    parameters: ["pointer"],
    result: "void",
  },
  // XSetTransientForHint @ include/Xlib.h:1939:12
  XSetTransientForHint: {
    parameters: ["pointer","u64","u64"],
    result: "i32",
  },
  // XActivateScreenSaver @ include/Xlib.h:1947:12
  XActivateScreenSaver: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XAddHost @ include/Xlib.h:1951:12
  XAddHost: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XAddHosts @ include/Xlib.h:1956:12
  XAddHosts: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XAddToExtensionList @ include/Xlib.h:1962:12
  XAddToExtensionList: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XAddToSaveSet @ include/Xlib.h:1967:12
  XAddToSaveSet: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XAllocColor @ include/Xlib.h:1972:15
  XAllocColor: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XAllocColorCells @ include/Xlib.h:1978:15
  XAllocColorCells: {
    parameters: ["pointer","u64","i32","pointer","u32","pointer","u32"],
    result: "i32",
  },
  // XAllocColorPlanes @ include/Xlib.h:1988:15
  XAllocColorPlanes: {
    parameters: ["pointer","u64","i32","pointer","i32","i32","i32","i32","pointer","pointer","pointer"],
    result: "i32",
  },
  // XAllocNamedColor @ include/Xlib.h:2002:15
  XAllocNamedColor: {
    parameters: ["pointer","u64","pointer","pointer","pointer"],
    result: "i32",
  },
  // XAllowEvents @ include/Xlib.h:2010:12
  XAllowEvents: {
    parameters: ["pointer","i32","u64"],
    result: "i32",
  },
  // XAutoRepeatOff @ include/Xlib.h:2016:12
  XAutoRepeatOff: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XAutoRepeatOn @ include/Xlib.h:2020:12
  XAutoRepeatOn: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XBell @ include/Xlib.h:2024:12
  XBell: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XBitmapBitOrder @ include/Xlib.h:2029:12
  XBitmapBitOrder: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XBitmapPad @ include/Xlib.h:2033:12
  XBitmapPad: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XBitmapUnit @ include/Xlib.h:2037:12
  XBitmapUnit: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XCellsOfScreen @ include/Xlib.h:2041:12
  XCellsOfScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XChangeActivePointerGrab @ include/Xlib.h:2045:12
  XChangeActivePointerGrab: {
    parameters: ["pointer","u32","u64","u64"],
    result: "i32",
  },
  // XChangeGC @ include/Xlib.h:2052:12
  XChangeGC: {
    parameters: ["pointer","pointer","u64","pointer"],
    result: "i32",
  },
  // XChangeKeyboardControl @ include/Xlib.h:2059:12
  XChangeKeyboardControl: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XChangeKeyboardMapping @ include/Xlib.h:2065:12
  XChangeKeyboardMapping: {
    parameters: ["pointer","i32","i32","pointer","i32"],
    result: "i32",
  },
  // XChangePointerControl @ include/Xlib.h:2073:12
  XChangePointerControl: {
    parameters: ["pointer","i32","i32","i32","i32","i32"],
    result: "i32",
  },
  // XChangeProperty @ include/Xlib.h:2082:12
  XChangeProperty: {
    parameters: ["pointer","u64","u64","u64","i32","i32","pointer","i32"],
    result: "i32",
  },
  // XChangeSaveSet @ include/Xlib.h:2093:12
  XChangeSaveSet: {
    parameters: ["pointer","u64","i32"],
    result: "i32",
  },
  // XChangeWindowAttributes @ include/Xlib.h:2099:12
  XChangeWindowAttributes: {
    parameters: ["pointer","u64","u64","pointer"],
    result: "i32",
  },
  // XCheckIfEvent @ include/Xlib.h:2106:13
  XCheckIfEvent: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XCheckMaskEvent @ include/Xlib.h:2117:13
  XCheckMaskEvent: {
    parameters: ["pointer","i64","pointer"],
    result: "i32",
  },
  // XCheckTypedEvent @ include/Xlib.h:2123:13
  XCheckTypedEvent: {
    parameters: ["pointer","i32","pointer"],
    result: "i32",
  },
  // XCheckTypedWindowEvent @ include/Xlib.h:2129:13
  XCheckTypedWindowEvent: {
    parameters: ["pointer","u64","i32","pointer"],
    result: "i32",
  },
  // XCheckWindowEvent @ include/Xlib.h:2136:13
  XCheckWindowEvent: {
    parameters: ["pointer","u64","i64","pointer"],
    result: "i32",
  },
  // XCirculateSubwindows @ include/Xlib.h:2143:12
  XCirculateSubwindows: {
    parameters: ["pointer","u64","i32"],
    result: "i32",
  },
  // XCirculateSubwindowsDown @ include/Xlib.h:2149:12
  XCirculateSubwindowsDown: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XCirculateSubwindowsUp @ include/Xlib.h:2154:12
  XCirculateSubwindowsUp: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XClearArea @ include/Xlib.h:2159:12
  XClearArea: {
    parameters: ["pointer","u64","i32","i32","u32","u32","i32"],
    result: "i32",
  },
  // XClearWindow @ include/Xlib.h:2169:12
  XClearWindow: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XCloseDisplay @ include/Xlib.h:2174:12
  XCloseDisplay: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XConfigureWindow @ include/Xlib.h:2178:12
  XConfigureWindow: {
    parameters: ["pointer","u64","u32","pointer"],
    result: "i32",
  },
  // XConnectionNumber @ include/Xlib.h:2185:12
  XConnectionNumber: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XConvertSelection @ include/Xlib.h:2189:12
  XConvertSelection: {
    parameters: ["pointer","u64","u64","u64","u64","u64"],
    result: "i32",
  },
  // XCopyArea @ include/Xlib.h:2198:12
  XCopyArea: {
    parameters: ["pointer","u64","u64","pointer","i32","i32","u32","u32","i32","i32"],
    result: "i32",
  },
  // XCopyGC @ include/Xlib.h:2211:12
  XCopyGC: {
    parameters: ["pointer","pointer","u64","pointer"],
    result: "i32",
  },
  // XCopyPlane @ include/Xlib.h:2218:12
  XCopyPlane: {
    parameters: ["pointer","u64","u64","pointer","i32","i32","u32","u32","i32","i32","u64"],
    result: "i32",
  },
  // XDefaultDepth @ include/Xlib.h:2232:12
  XDefaultDepth: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XDefaultDepthOfScreen @ include/Xlib.h:2237:12
  XDefaultDepthOfScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XDefaultScreen @ include/Xlib.h:2241:12
  XDefaultScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XDefineCursor @ include/Xlib.h:2245:12
  XDefineCursor: {
    parameters: ["pointer","u64","u64"],
    result: "i32",
  },
  // XDeleteProperty @ include/Xlib.h:2251:12
  XDeleteProperty: {
    parameters: ["pointer","u64","u64"],
    result: "i32",
  },
  // XDestroyWindow @ include/Xlib.h:2257:12
  XDestroyWindow: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XDestroySubwindows @ include/Xlib.h:2262:12
  XDestroySubwindows: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XDoesBackingStore @ include/Xlib.h:2267:12
  XDoesBackingStore: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XDoesSaveUnders @ include/Xlib.h:2271:13
  XDoesSaveUnders: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XDisableAccessControl @ include/Xlib.h:2275:12
  XDisableAccessControl: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XDisplayCells @ include/Xlib.h:2280:12
  XDisplayCells: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XDisplayHeight @ include/Xlib.h:2285:12
  XDisplayHeight: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XDisplayHeightMM @ include/Xlib.h:2290:12
  XDisplayHeightMM: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XDisplayKeycodes @ include/Xlib.h:2295:12
  XDisplayKeycodes: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // XDisplayPlanes @ include/Xlib.h:2301:12
  XDisplayPlanes: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XDisplayWidth @ include/Xlib.h:2306:12
  XDisplayWidth: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XDisplayWidthMM @ include/Xlib.h:2311:12
  XDisplayWidthMM: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XDrawArc @ include/Xlib.h:2316:12
  XDrawArc: {
    parameters: ["pointer","u64","pointer","i32","i32","u32","u32","i32","i32"],
    result: "i32",
  },
  // XDrawArcs @ include/Xlib.h:2328:12
  XDrawArcs: {
    parameters: ["pointer","u64","pointer","pointer","i32"],
    result: "i32",
  },
  // XDrawImageString @ include/Xlib.h:2336:12
  XDrawImageString: {
    parameters: ["pointer","u64","pointer","i32","i32","pointer","i32"],
    result: "i32",
  },
  // XDrawImageString16 @ include/Xlib.h:2346:12
  XDrawImageString16: {
    parameters: ["pointer","u64","pointer","i32","i32","pointer","i32"],
    result: "i32",
  },
  // XDrawLine @ include/Xlib.h:2356:12
  XDrawLine: {
    parameters: ["pointer","u64","pointer","i32","i32","i32","i32"],
    result: "i32",
  },
  // XDrawLines @ include/Xlib.h:2366:12
  XDrawLines: {
    parameters: ["pointer","u64","pointer","pointer","i32","i32"],
    result: "i32",
  },
  // XDrawPoint @ include/Xlib.h:2375:12
  XDrawPoint: {
    parameters: ["pointer","u64","pointer","i32","i32"],
    result: "i32",
  },
  // XDrawPoints @ include/Xlib.h:2383:12
  XDrawPoints: {
    parameters: ["pointer","u64","pointer","pointer","i32","i32"],
    result: "i32",
  },
  // XDrawRectangle @ include/Xlib.h:2392:12
  XDrawRectangle: {
    parameters: ["pointer","u64","pointer","i32","i32","u32","u32"],
    result: "i32",
  },
  // XDrawRectangles @ include/Xlib.h:2402:12
  XDrawRectangles: {
    parameters: ["pointer","u64","pointer","pointer","i32"],
    result: "i32",
  },
  // XDrawSegments @ include/Xlib.h:2410:12
  XDrawSegments: {
    parameters: ["pointer","u64","pointer","pointer","i32"],
    result: "i32",
  },
  // XDrawString @ include/Xlib.h:2418:12
  XDrawString: {
    parameters: ["pointer","u64","pointer","i32","i32","pointer","i32"],
    result: "i32",
  },
  // XDrawString16 @ include/Xlib.h:2428:12
  XDrawString16: {
    parameters: ["pointer","u64","pointer","i32","i32","pointer","i32"],
    result: "i32",
  },
  // XDrawText @ include/Xlib.h:2438:12
  XDrawText: {
    parameters: ["pointer","u64","pointer","i32","i32","pointer","i32"],
    result: "i32",
  },
  // XDrawText16 @ include/Xlib.h:2448:12
  XDrawText16: {
    parameters: ["pointer","u64","pointer","i32","i32","pointer","i32"],
    result: "i32",
  },
  // XEnableAccessControl @ include/Xlib.h:2458:12
  XEnableAccessControl: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XEventsQueued @ include/Xlib.h:2462:12
  XEventsQueued: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XFetchName @ include/Xlib.h:2467:15
  XFetchName: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XFillArc @ include/Xlib.h:2473:12
  XFillArc: {
    parameters: ["pointer","u64","pointer","i32","i32","u32","u32","i32","i32"],
    result: "i32",
  },
  // XFillArcs @ include/Xlib.h:2485:12
  XFillArcs: {
    parameters: ["pointer","u64","pointer","pointer","i32"],
    result: "i32",
  },
  // XFillPolygon @ include/Xlib.h:2493:12
  XFillPolygon: {
    parameters: ["pointer","u64","pointer","pointer","i32","i32","i32"],
    result: "i32",
  },
  // XFillRectangle @ include/Xlib.h:2503:12
  XFillRectangle: {
    parameters: ["pointer","u64","pointer","i32","i32","u32","u32"],
    result: "i32",
  },
  // XFillRectangles @ include/Xlib.h:2513:12
  XFillRectangles: {
    parameters: ["pointer","u64","pointer","pointer","i32"],
    result: "i32",
  },
  // XFlush @ include/Xlib.h:2521:12
  XFlush: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XForceScreenSaver @ include/Xlib.h:2525:12
  XForceScreenSaver: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XFree @ include/Xlib.h:2530:12
  XFree: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XFreeColormap @ include/Xlib.h:2534:12
  XFreeColormap: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XFreeColors @ include/Xlib.h:2539:12
  XFreeColors: {
    parameters: ["pointer","u64","pointer","i32","u64"],
    result: "i32",
  },
  // XFreeCursor @ include/Xlib.h:2547:12
  XFreeCursor: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XFreeExtensionList @ include/Xlib.h:2552:12
  XFreeExtensionList: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XFreeFont @ include/Xlib.h:2556:12
  XFreeFont: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XFreeFontInfo @ include/Xlib.h:2561:12
  XFreeFontInfo: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XFreeFontNames @ include/Xlib.h:2567:12
  XFreeFontNames: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XFreeFontPath @ include/Xlib.h:2571:12
  XFreeFontPath: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XFreeGC @ include/Xlib.h:2575:12
  XFreeGC: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XFreeModifiermap @ include/Xlib.h:2580:12
  XFreeModifiermap: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XFreePixmap @ include/Xlib.h:2584:12
  XFreePixmap: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XGeometry @ include/Xlib.h:2589:12
  XGeometry: {
    parameters: ["pointer","i32","pointer","pointer","u32","u32","u32","i32","i32","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XGetErrorDatabaseText @ include/Xlib.h:2605:12
  XGetErrorDatabaseText: {
    parameters: ["pointer","pointer","pointer","pointer","pointer","i32"],
    result: "i32",
  },
  // XGetErrorText @ include/Xlib.h:2614:12
  XGetErrorText: {
    parameters: ["pointer","i32","pointer","i32"],
    result: "i32",
  },
  // XGetFontProperty @ include/Xlib.h:2621:13
  XGetFontProperty: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XGetGCValues @ include/Xlib.h:2627:15
  XGetGCValues: {
    parameters: ["pointer","pointer","u64","pointer"],
    result: "i32",
  },
  // XGetGeometry @ include/Xlib.h:2634:15
  XGetGeometry: {
    parameters: ["pointer","u64","pointer","pointer","pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XGetIconName @ include/Xlib.h:2646:15
  XGetIconName: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XGetInputFocus @ include/Xlib.h:2652:12
  XGetInputFocus: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // XGetKeyboardControl @ include/Xlib.h:2658:12
  XGetKeyboardControl: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XGetPointerControl @ include/Xlib.h:2663:12
  XGetPointerControl: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XGetPointerMapping @ include/Xlib.h:2670:12
  XGetPointerMapping: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XGetScreenSaver @ include/Xlib.h:2676:12
  XGetScreenSaver: {
    parameters: ["pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XGetTransientForHint @ include/Xlib.h:2684:15
  XGetTransientForHint: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XGetWindowProperty @ include/Xlib.h:2690:12
  XGetWindowProperty: {
    parameters: ["pointer","u64","u64","i64","i64","i32","u64","pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XGetWindowAttributes @ include/Xlib.h:2705:15
  XGetWindowAttributes: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XGrabButton @ include/Xlib.h:2711:12
  XGrabButton: {
    parameters: ["pointer","u32","u32","u64","i32","u32","i32","i32","u64","u64"],
    result: "i32",
  },
  // XGrabKey @ include/Xlib.h:2724:12
  XGrabKey: {
    parameters: ["pointer","i32","u32","u64","i32","i32","i32"],
    result: "i32",
  },
  // XGrabKeyboard @ include/Xlib.h:2734:12
  XGrabKeyboard: {
    parameters: ["pointer","u64","i32","i32","i32","u64"],
    result: "i32",
  },
  // XGrabPointer @ include/Xlib.h:2743:12
  XGrabPointer: {
    parameters: ["pointer","u64","i32","u32","i32","i32","u64","u64","u64"],
    result: "i32",
  },
  // XGrabServer @ include/Xlib.h:2755:12
  XGrabServer: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XHeightMMOfScreen @ include/Xlib.h:2759:12
  XHeightMMOfScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XHeightOfScreen @ include/Xlib.h:2763:12
  XHeightOfScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XIfEvent @ include/Xlib.h:2767:12
  XIfEvent: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XImageByteOrder @ include/Xlib.h:2778:12
  XImageByteOrder: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XInstallColormap @ include/Xlib.h:2782:12
  XInstallColormap: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XKeysymToKeycode @ include/Xlib.h:2787:16
  XKeysymToKeycode: {
    parameters: ["pointer","u64"],
    result: "u8",
  },
  // XKillClient @ include/Xlib.h:2792:12
  XKillClient: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XLookupColor @ include/Xlib.h:2797:15
  XLookupColor: {
    parameters: ["pointer","u64","pointer","pointer","pointer"],
    result: "i32",
  },
  // XLowerWindow @ include/Xlib.h:2805:12
  XLowerWindow: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XMapRaised @ include/Xlib.h:2810:12
  XMapRaised: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XMapSubwindows @ include/Xlib.h:2815:12
  XMapSubwindows: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XMapWindow @ include/Xlib.h:2820:12
  XMapWindow: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XMaskEvent @ include/Xlib.h:2825:12
  XMaskEvent: {
    parameters: ["pointer","i64","pointer"],
    result: "i32",
  },
  // XMaxCmapsOfScreen @ include/Xlib.h:2831:12
  XMaxCmapsOfScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XMinCmapsOfScreen @ include/Xlib.h:2835:12
  XMinCmapsOfScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XMoveResizeWindow @ include/Xlib.h:2839:12
  XMoveResizeWindow: {
    parameters: ["pointer","u64","i32","i32","u32","u32"],
    result: "i32",
  },
  // XMoveWindow @ include/Xlib.h:2848:12
  XMoveWindow: {
    parameters: ["pointer","u64","i32","i32"],
    result: "i32",
  },
  // XNextEvent @ include/Xlib.h:2855:12
  XNextEvent: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XNoOp @ include/Xlib.h:2860:12
  XNoOp: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XParseColor @ include/Xlib.h:2864:15
  XParseColor: {
    parameters: ["pointer","u64","pointer","pointer"],
    result: "i32",
  },
  // XParseGeometry @ include/Xlib.h:2871:12
  XParseGeometry: {
    parameters: ["pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XPeekEvent @ include/Xlib.h:2879:12
  XPeekEvent: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XPeekIfEvent @ include/Xlib.h:2884:12
  XPeekIfEvent: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XPending @ include/Xlib.h:2895:12
  XPending: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XPlanesOfScreen @ include/Xlib.h:2899:12
  XPlanesOfScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XProtocolRevision @ include/Xlib.h:2903:12
  XProtocolRevision: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XProtocolVersion @ include/Xlib.h:2907:12
  XProtocolVersion: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XPutBackEvent @ include/Xlib.h:2912:12
  XPutBackEvent: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XPutImage @ include/Xlib.h:2917:12
  XPutImage: {
    parameters: ["pointer","u64","pointer","pointer","i32","i32","i32","i32","u32","u32"],
    result: "i32",
  },
  // XQLength @ include/Xlib.h:2930:12
  XQLength: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XQueryBestCursor @ include/Xlib.h:2934:15
  XQueryBestCursor: {
    parameters: ["pointer","u64","u32","u32","pointer","pointer"],
    result: "i32",
  },
  // XQueryBestSize @ include/Xlib.h:2943:15
  XQueryBestSize: {
    parameters: ["pointer","i32","u64","u32","u32","pointer","pointer"],
    result: "i32",
  },
  // XQueryBestStipple @ include/Xlib.h:2953:15
  XQueryBestStipple: {
    parameters: ["pointer","u64","u32","u32","pointer","pointer"],
    result: "i32",
  },
  // XQueryBestTile @ include/Xlib.h:2962:15
  XQueryBestTile: {
    parameters: ["pointer","u64","u32","u32","pointer","pointer"],
    result: "i32",
  },
  // XQueryColor @ include/Xlib.h:2971:12
  XQueryColor: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XQueryColors @ include/Xlib.h:2977:12
  XQueryColors: {
    parameters: ["pointer","u64","pointer","i32"],
    result: "i32",
  },
  // XQueryExtension @ include/Xlib.h:2984:13
  XQueryExtension: {
    parameters: ["pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XQueryPointer @ include/Xlib.h:2997:13
  XQueryPointer: {
    parameters: ["pointer","u64","pointer","pointer","pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XQueryTextExtents @ include/Xlib.h:3009:12
  XQueryTextExtents: {
    parameters: ["pointer","u64","pointer","i32","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XQueryTextExtents16 @ include/Xlib.h:3020:12
  XQueryTextExtents16: {
    parameters: ["pointer","u64","pointer","i32","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XQueryTree @ include/Xlib.h:3031:15
  XQueryTree: {
    parameters: ["pointer","u64","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XRaiseWindow @ include/Xlib.h:3040:12
  XRaiseWindow: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XReadBitmapFile @ include/Xlib.h:3045:12
  XReadBitmapFile: {
    parameters: ["pointer","u64","pointer","pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XReadBitmapFileData @ include/Xlib.h:3056:12
  XReadBitmapFileData: {
    parameters: ["pointer","pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XRebindKeysym @ include/Xlib.h:3065:12
  XRebindKeysym: {
    parameters: ["pointer","u64","pointer","i32","pointer","i32"],
    result: "i32",
  },
  // XRecolorCursor @ include/Xlib.h:3074:12
  XRecolorCursor: {
    parameters: ["pointer","u64","pointer","pointer"],
    result: "i32",
  },
  // XRefreshKeyboardMapping @ include/Xlib.h:3081:12
  XRefreshKeyboardMapping: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XRemoveFromSaveSet @ include/Xlib.h:3085:12
  XRemoveFromSaveSet: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XRemoveHost @ include/Xlib.h:3090:12
  XRemoveHost: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XRemoveHosts @ include/Xlib.h:3095:12
  XRemoveHosts: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XReparentWindow @ include/Xlib.h:3101:12
  XReparentWindow: {
    parameters: ["pointer","u64","u64","i32","i32"],
    result: "i32",
  },
  // XResetScreenSaver @ include/Xlib.h:3109:12
  XResetScreenSaver: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XResizeWindow @ include/Xlib.h:3113:12
  XResizeWindow: {
    parameters: ["pointer","u64","u32","u32"],
    result: "i32",
  },
  // XRestackWindows @ include/Xlib.h:3120:12
  XRestackWindows: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XRotateBuffers @ include/Xlib.h:3126:12
  XRotateBuffers: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XRotateWindowProperties @ include/Xlib.h:3131:12
  XRotateWindowProperties: {
    parameters: ["pointer","u64","pointer","i32","i32"],
    result: "i32",
  },
  // XScreenCount @ include/Xlib.h:3139:12
  XScreenCount: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XSelectInput @ include/Xlib.h:3143:12
  XSelectInput: {
    parameters: ["pointer","u64","i64"],
    result: "i32",
  },
  // XSendEvent @ include/Xlib.h:3149:15
  XSendEvent: {
    parameters: ["pointer","u64","i32","i64","pointer"],
    result: "i32",
  },
  // XSetAccessControl @ include/Xlib.h:3157:12
  XSetAccessControl: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XSetArcMode @ include/Xlib.h:3162:12
  XSetArcMode: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XSetBackground @ include/Xlib.h:3168:12
  XSetBackground: {
    parameters: ["pointer","pointer","u64"],
    result: "i32",
  },
  // XSetClipMask @ include/Xlib.h:3174:12
  XSetClipMask: {
    parameters: ["pointer","pointer","u64"],
    result: "i32",
  },
  // XSetClipOrigin @ include/Xlib.h:3180:12
  XSetClipOrigin: {
    parameters: ["pointer","pointer","i32","i32"],
    result: "i32",
  },
  // XSetClipRectangles @ include/Xlib.h:3187:12
  XSetClipRectangles: {
    parameters: ["pointer","pointer","i32","i32","pointer","i32","i32"],
    result: "i32",
  },
  // XSetCloseDownMode @ include/Xlib.h:3197:12
  XSetCloseDownMode: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XSetCommand @ include/Xlib.h:3202:12
  XSetCommand: {
    parameters: ["pointer","u64","pointer","i32"],
    result: "i32",
  },
  // XSetDashes @ include/Xlib.h:3209:12
  XSetDashes: {
    parameters: ["pointer","pointer","i32","pointer","i32"],
    result: "i32",
  },
  // XSetFillRule @ include/Xlib.h:3217:12
  XSetFillRule: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XSetFillStyle @ include/Xlib.h:3223:12
  XSetFillStyle: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XSetFont @ include/Xlib.h:3229:12
  XSetFont: {
    parameters: ["pointer","pointer","u64"],
    result: "i32",
  },
  // XSetFontPath @ include/Xlib.h:3235:12
  XSetFontPath: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XSetForeground @ include/Xlib.h:3241:12
  XSetForeground: {
    parameters: ["pointer","pointer","u64"],
    result: "i32",
  },
  // XSetFunction @ include/Xlib.h:3247:12
  XSetFunction: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XSetGraphicsExposures @ include/Xlib.h:3253:12
  XSetGraphicsExposures: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XSetIconName @ include/Xlib.h:3259:12
  XSetIconName: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XSetInputFocus @ include/Xlib.h:3265:12
  XSetInputFocus: {
    parameters: ["pointer","u64","i32","u64"],
    result: "i32",
  },
  // XSetLineAttributes @ include/Xlib.h:3272:12
  XSetLineAttributes: {
    parameters: ["pointer","pointer","u32","i32","i32","i32"],
    result: "i32",
  },
  // XSetModifierMapping @ include/Xlib.h:3281:12
  XSetModifierMapping: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XSetPlaneMask @ include/Xlib.h:3286:12
  XSetPlaneMask: {
    parameters: ["pointer","pointer","u64"],
    result: "i32",
  },
  // XSetPointerMapping @ include/Xlib.h:3292:12
  XSetPointerMapping: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XSetScreenSaver @ include/Xlib.h:3298:12
  XSetScreenSaver: {
    parameters: ["pointer","i32","i32","i32","i32"],
    result: "i32",
  },
  // XSetSelectionOwner @ include/Xlib.h:3306:12
  XSetSelectionOwner: {
    parameters: ["pointer","u64","u64","u64"],
    result: "i32",
  },
  // XSetState @ include/Xlib.h:3313:12
  XSetState: {
    parameters: ["pointer","pointer","u64","u64","i32","u64"],
    result: "i32",
  },
  // XSetStipple @ include/Xlib.h:3322:12
  XSetStipple: {
    parameters: ["pointer","pointer","u64"],
    result: "i32",
  },
  // XSetSubwindowMode @ include/Xlib.h:3328:12
  XSetSubwindowMode: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XSetTSOrigin @ include/Xlib.h:3334:12
  XSetTSOrigin: {
    parameters: ["pointer","pointer","i32","i32"],
    result: "i32",
  },
  // XSetTile @ include/Xlib.h:3341:12
  XSetTile: {
    parameters: ["pointer","pointer","u64"],
    result: "i32",
  },
  // XSetWindowBackground @ include/Xlib.h:3347:12
  XSetWindowBackground: {
    parameters: ["pointer","u64","u64"],
    result: "i32",
  },
  // XSetWindowBackgroundPixmap @ include/Xlib.h:3353:12
  XSetWindowBackgroundPixmap: {
    parameters: ["pointer","u64","u64"],
    result: "i32",
  },
  // XSetWindowBorder @ include/Xlib.h:3359:12
  XSetWindowBorder: {
    parameters: ["pointer","u64","u64"],
    result: "i32",
  },
  // XSetWindowBorderPixmap @ include/Xlib.h:3365:12
  XSetWindowBorderPixmap: {
    parameters: ["pointer","u64","u64"],
    result: "i32",
  },
  // XSetWindowBorderWidth @ include/Xlib.h:3371:12
  XSetWindowBorderWidth: {
    parameters: ["pointer","u64","u32"],
    result: "i32",
  },
  // XSetWindowColormap @ include/Xlib.h:3377:12
  XSetWindowColormap: {
    parameters: ["pointer","u64","u64"],
    result: "i32",
  },
  // XStoreBuffer @ include/Xlib.h:3383:12
  XStoreBuffer: {
    parameters: ["pointer","pointer","i32","i32"],
    result: "i32",
  },
  // XStoreBytes @ include/Xlib.h:3390:12
  XStoreBytes: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XStoreColor @ include/Xlib.h:3396:12
  XStoreColor: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XStoreColors @ include/Xlib.h:3402:12
  XStoreColors: {
    parameters: ["pointer","u64","pointer","i32"],
    result: "i32",
  },
  // XStoreName @ include/Xlib.h:3409:12
  XStoreName: {
    parameters: ["pointer","u64","pointer"],
    result: "i32",
  },
  // XStoreNamedColor @ include/Xlib.h:3415:12
  XStoreNamedColor: {
    parameters: ["pointer","u64","pointer","u64","i32"],
    result: "i32",
  },
  // XSync @ include/Xlib.h:3423:12
  XSync: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XTextExtents @ include/Xlib.h:3428:12
  XTextExtents: {
    parameters: ["pointer","pointer","i32","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XTextExtents16 @ include/Xlib.h:3438:12
  XTextExtents16: {
    parameters: ["pointer","pointer","i32","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XTextWidth @ include/Xlib.h:3448:12
  XTextWidth: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XTextWidth16 @ include/Xlib.h:3454:12
  XTextWidth16: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XTranslateCoordinates @ include/Xlib.h:3460:13
  XTranslateCoordinates: {
    parameters: ["pointer","u64","u64","i32","i32","pointer","pointer","pointer"],
    result: "i32",
  },
  // XUndefineCursor @ include/Xlib.h:3471:12
  XUndefineCursor: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XUngrabButton @ include/Xlib.h:3476:12
  XUngrabButton: {
    parameters: ["pointer","u32","u32","u64"],
    result: "i32",
  },
  // XUngrabKey @ include/Xlib.h:3483:12
  XUngrabKey: {
    parameters: ["pointer","i32","u32","u64"],
    result: "i32",
  },
  // XUngrabKeyboard @ include/Xlib.h:3490:12
  XUngrabKeyboard: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XUngrabPointer @ include/Xlib.h:3495:12
  XUngrabPointer: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XUngrabServer @ include/Xlib.h:3500:12
  XUngrabServer: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XUninstallColormap @ include/Xlib.h:3504:12
  XUninstallColormap: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XUnloadFont @ include/Xlib.h:3509:12
  XUnloadFont: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XUnmapSubwindows @ include/Xlib.h:3514:12
  XUnmapSubwindows: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XUnmapWindow @ include/Xlib.h:3519:12
  XUnmapWindow: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XVendorRelease @ include/Xlib.h:3524:12
  XVendorRelease: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XWarpPointer @ include/Xlib.h:3528:12
  XWarpPointer: {
    parameters: ["pointer","u64","u64","i32","i32","u32","u32","i32","i32"],
    result: "i32",
  },
  // XWidthMMOfScreen @ include/Xlib.h:3540:12
  XWidthMMOfScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XWidthOfScreen @ include/Xlib.h:3544:12
  XWidthOfScreen: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XWindowEvent @ include/Xlib.h:3548:12
  XWindowEvent: {
    parameters: ["pointer","u64","i64","pointer"],
    result: "i32",
  },
  // XWriteBitmapFile @ include/Xlib.h:3555:12
  XWriteBitmapFile: {
    parameters: ["pointer","pointer","u64","u32","u32","i32","i32"],
    result: "i32",
  },
  // XSupportsLocale @ include/Xlib.h:3565:13
  XSupportsLocale: {
    parameters: [],
    result: "i32",
  },
  // XSetLocaleModifiers @ include/Xlib.h:3567:14
  XSetLocaleModifiers: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XOpenOM @ include/Xlib.h:3571:12
  XOpenOM: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "pointer",
  },
  // XCloseOM @ include/Xlib.h:3578:15
  XCloseOM: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XDisplayOfOM @ include/Xlib.h:3592:17
  XDisplayOfOM: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XLocaleOfOM @ include/Xlib.h:3596:14
  XLocaleOfOM: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XDestroyOC @ include/Xlib.h:3605:13
  XDestroyOC: {
    parameters: ["pointer"],
    result: "void",
  },
  // XOMOfOC @ include/Xlib.h:3609:12
  XOMOfOC: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XCreateFontSet @ include/Xlib.h:3623:17
  XCreateFontSet: {
    parameters: ["pointer","pointer","pointer","pointer","pointer"],
    result: "pointer",
  },
  // XFreeFontSet @ include/Xlib.h:3631:13
  XFreeFontSet: {
    parameters: ["pointer","pointer"],
    result: "void",
  },
  // XFontsOfFontSet @ include/Xlib.h:3636:12
  XFontsOfFontSet: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // XBaseFontNameListOfFontSet @ include/Xlib.h:3642:14
  XBaseFontNameListOfFontSet: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XLocaleOfFontSet @ include/Xlib.h:3646:14
  XLocaleOfFontSet: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XContextDependentDrawing @ include/Xlib.h:3650:13
  XContextDependentDrawing: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XDirectionalDependentDrawing @ include/Xlib.h:3654:13
  XDirectionalDependentDrawing: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XContextualDrawing @ include/Xlib.h:3658:13
  XContextualDrawing: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XExtentsOfFontSet @ include/Xlib.h:3662:25
  XExtentsOfFontSet: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XmbTextEscapement @ include/Xlib.h:3666:12
  XmbTextEscapement: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XwcTextEscapement @ include/Xlib.h:3672:12
  XwcTextEscapement: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // Xutf8TextEscapement @ include/Xlib.h:3678:12
  Xutf8TextEscapement: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // XmbTextExtents @ include/Xlib.h:3684:12
  XmbTextExtents: {
    parameters: ["pointer","pointer","i32","pointer","pointer"],
    result: "i32",
  },
  // XwcTextExtents @ include/Xlib.h:3692:12
  XwcTextExtents: {
    parameters: ["pointer","pointer","i32","pointer","pointer"],
    result: "i32",
  },
  // Xutf8TextExtents @ include/Xlib.h:3700:12
  Xutf8TextExtents: {
    parameters: ["pointer","pointer","i32","pointer","pointer"],
    result: "i32",
  },
  // XmbTextPerCharExtents @ include/Xlib.h:3708:15
  XmbTextPerCharExtents: {
    parameters: ["pointer","pointer","i32","pointer","pointer","i32","pointer","pointer","pointer"],
    result: "i32",
  },
  // XwcTextPerCharExtents @ include/Xlib.h:3720:15
  XwcTextPerCharExtents: {
    parameters: ["pointer","pointer","i32","pointer","pointer","i32","pointer","pointer","pointer"],
    result: "i32",
  },
  // Xutf8TextPerCharExtents @ include/Xlib.h:3732:15
  Xutf8TextPerCharExtents: {
    parameters: ["pointer","pointer","i32","pointer","pointer","i32","pointer","pointer","pointer"],
    result: "i32",
  },
  // XmbDrawText @ include/Xlib.h:3744:13
  XmbDrawText: {
    parameters: ["pointer","u64","pointer","i32","i32","pointer","i32"],
    result: "void",
  },
  // XwcDrawText @ include/Xlib.h:3754:13
  XwcDrawText: {
    parameters: ["pointer","u64","pointer","i32","i32","pointer","i32"],
    result: "void",
  },
  // Xutf8DrawText @ include/Xlib.h:3764:13
  Xutf8DrawText: {
    parameters: ["pointer","u64","pointer","i32","i32","pointer","i32"],
    result: "void",
  },
  // XmbDrawString @ include/Xlib.h:3774:13
  XmbDrawString: {
    parameters: ["pointer","u64","pointer","pointer","i32","i32","pointer","i32"],
    result: "void",
  },
  // XwcDrawString @ include/Xlib.h:3785:13
  XwcDrawString: {
    parameters: ["pointer","u64","pointer","pointer","i32","i32","pointer","i32"],
    result: "void",
  },
  // Xutf8DrawString @ include/Xlib.h:3796:13
  Xutf8DrawString: {
    parameters: ["pointer","u64","pointer","pointer","i32","i32","pointer","i32"],
    result: "void",
  },
  // XmbDrawImageString @ include/Xlib.h:3807:13
  XmbDrawImageString: {
    parameters: ["pointer","u64","pointer","pointer","i32","i32","pointer","i32"],
    result: "void",
  },
  // XwcDrawImageString @ include/Xlib.h:3818:13
  XwcDrawImageString: {
    parameters: ["pointer","u64","pointer","pointer","i32","i32","pointer","i32"],
    result: "void",
  },
  // Xutf8DrawImageString @ include/Xlib.h:3829:13
  Xutf8DrawImageString: {
    parameters: ["pointer","u64","pointer","pointer","i32","i32","pointer","i32"],
    result: "void",
  },
  // XOpenIM @ include/Xlib.h:3840:12
  XOpenIM: {
    parameters: ["pointer","pointer","pointer","pointer"],
    result: "pointer",
  },
  // XCloseIM @ include/Xlib.h:3847:15
  XCloseIM: {
    parameters: ["pointer"],
    result: "i32",
  },
  // XDisplayOfIM @ include/Xlib.h:3859:17
  XDisplayOfIM: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XLocaleOfIM @ include/Xlib.h:3863:14
  XLocaleOfIM: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XDestroyIC @ include/Xlib.h:3871:13
  XDestroyIC: {
    parameters: ["pointer"],
    result: "void",
  },
  // XSetICFocus @ include/Xlib.h:3875:13
  XSetICFocus: {
    parameters: ["pointer"],
    result: "void",
  },
  // XUnsetICFocus @ include/Xlib.h:3879:13
  XUnsetICFocus: {
    parameters: ["pointer"],
    result: "void",
  },
  // XwcResetIC @ include/Xlib.h:3883:17
  XwcResetIC: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XmbResetIC @ include/Xlib.h:3887:14
  XmbResetIC: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // Xutf8ResetIC @ include/Xlib.h:3891:14
  Xutf8ResetIC: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XIMOfIC @ include/Xlib.h:3903:12
  XIMOfIC: {
    parameters: ["pointer"],
    result: "pointer",
  },
  // XFilterEvent @ include/Xlib.h:3907:13
  XFilterEvent: {
    parameters: ["pointer","u64"],
    result: "i32",
  },
  // XmbLookupString @ include/Xlib.h:3912:12
  XmbLookupString: {
    parameters: ["pointer","pointer","pointer","i32","pointer","pointer"],
    result: "i32",
  },
  // XwcLookupString @ include/Xlib.h:3921:12
  XwcLookupString: {
    parameters: ["pointer","pointer","pointer","i32","pointer","pointer"],
    result: "i32",
  },
  // Xutf8LookupString @ include/Xlib.h:3930:12
  Xutf8LookupString: {
    parameters: ["pointer","pointer","pointer","i32","pointer","pointer"],
    result: "i32",
  },
  // XRegisterIMInstantiateCallback @ include/Xlib.h:3945:13
  XRegisterIMInstantiateCallback: {
    parameters: ["pointer","pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XUnregisterIMInstantiateCallback @ include/Xlib.h:3954:13
  XUnregisterIMInstantiateCallback: {
    parameters: ["pointer","pointer","pointer","pointer","pointer","pointer"],
    result: "i32",
  },
  // XInternalConnectionNumbers @ include/Xlib.h:3972:15
  XInternalConnectionNumbers: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // XProcessInternalConnection @ include/Xlib.h:3978:13
  XProcessInternalConnection: {
    parameters: ["pointer","i32"],
    result: "void",
  },
  // XAddConnectionWatch @ include/Xlib.h:3983:15
  XAddConnectionWatch: {
    parameters: ["pointer","pointer","pointer"],
    result: "i32",
  },
  // XRemoveConnectionWatch @ include/Xlib.h:3989:13
  XRemoveConnectionWatch: {
    parameters: ["pointer","pointer","pointer"],
    result: "void",
  },
  // XSetAuthorization @ include/Xlib.h:3995:13
  XSetAuthorization: {
    parameters: ["pointer","i32","pointer","i32"],
    result: "void",
  },
  // _Xmbtowc @ include/Xlib.h:4002:12
  _Xmbtowc: {
    parameters: ["pointer","pointer","i32"],
    result: "i32",
  },
  // _Xwctomb @ include/Xlib.h:4008:12
  _Xwctomb: {
    parameters: ["pointer","i32"],
    result: "i32",
  },
  // XGetEventData @ include/Xlib.h:4013:13
  XGetEventData: {
    parameters: ["pointer","pointer"],
    result: "i32",
  },
  // XFreeEventData @ include/Xlib.h:4018:13
  XFreeEventData: {
    parameters: ["pointer","pointer"],
    result: "void",
  }
} as const;

const { symbols } = Deno.dlopen("libXlib.so", _);

export default symbols;

